### ISSUE TITLE
opencv的mat如何显示到窗口中

### ISSUE THREAD

**Issue by fangdichan** [ying32/govcl#100]
我应该如何操作，可以在label控件（或者其他控件）中显示opencv的mat数据，实时播放摄像头图像。谢谢

**Comment by ying32** [comment]
没用过opencv，你如果想要显示图片可以用`TImage`控件，至于格式你必须要将opencv的转为lcl可支持的，比如jpg,png,bmp之类的常规格式。

**Comment by fangdichan** [comment]
> 没用过opencv，你如果想要显示图片可以用`TImage`控件，至于格式你必须要将opencv的mat数据转为lcl可支持的，比如jpg,png,bmp之类的常规格式。

嗯，自己摸索了一下，目前把opencv的数据转为bmp，在timage中显示，可以正常工作，非常感谢。
