### ISSUE TITLE
error when updating package

### ISSUE THREAD

**Issue by MarcelXia** [ying32/govcl#102]
go get -u ./...
# github.com/ying32/govcl/vcl/api
../../../go/pkg/mod/github.com/ying32/govcl@v2.2.0+incompatible/vcl/api/importFuncsAuto.go:392:53: undefined: TMessage

when I do "normal" way::
go get -u github.com/ying32/govcl
no complaints until I run the example:
vendor/github.com/ying32/govcl/vcl/api/importFuncsAuto.go:392:53: undefined: TMessage

**Comment by ying32** [comment]
GOARCH=arm64?

**Comment by MarcelXia** [comment]
Sorry, but what do you mean by that?
(I have a Mac M1, if that's your question)

**Comment by ying32** [comment]
Because I don't have an M1 machine, I didn't support M1, but some friends have already submitted M1 support.（因为我没有M1的机器，所以我没有去支持M1，不过已经有朋友提交了M1的支持。）

**Comment by MarcelXia** [comment]
Updated it but there's still something wrong:
# github.com/ying32/govcl/vcl/api
vendor/github.com/ying32/govcl/vcl/api/importFuncsAuto.go:392:53: undefined: TMessage

**Comment by ying32** [comment]
This guy has m1 support https://github.com/rarnu/govcl/tree/dev-m1, https://github.com/rarnu/govcl/blob/dev-m1/vcl/dylib/liblcl .dylib, but I haven't tested it.
