### ISSUE TITLE
是否可以把miniWebview在windows上改为Edge实现

### ISSUE THREAD

**Issue by itgowo** [ying32/govcl#104]
感谢作者提供这个库，让我简单实现了一些功能，期望作者用Webview2实现miniWebview

目前我要做一个界面，期望是用xtermjs实现H5，用一个webview加载，目前IE11是不能稳定支持的；

目前我已实现：
**Window**：用Webview2（Edge），实现创建Webview组件，再调用[put_parentwindow （Edge文档）](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2controller?view=webview2-1.0.622.22#put_parentwindow)，将Webview2组件放到TForm中的panel上（WebPanel.Handle()）

**Mac**：用默认的MiniWebview组件

**Linux**：不在考虑范围内

为什么我不用原生或者其他组件实现terminal？没找到。。。。，fyne有个demo，bug多，于是采用h5折中方案

**Comment by ying32** [comment]
不好意思，这个估计暂时没法满足你的要求了。。。 你可以看看里面的那个 miniblink的是不是能满足你在windows下的需求。

**Comment by itgowo** [comment]
好的，希望作者越做越好
