### ISSUE TITLE
How do I make the message "Library Version: 2.2.0" not appear when I launch an application ?

### ISSUE THREAD

**Issue by Tomatin** [ying32/govcl#108]
Hi. Excellent solution for GUI apps !!! 
What options should I pass to go build so that no console message appears ?

Thanks in advance !

**Comment by Tomatin** [comment]
I already found the solution:
go build -ldflags -H=windowsgui test.go

**Comment by ying32** [comment]
This prompt cannot be removed, but you can modify the source code to remove this prompt. You just hide the console this way.
