### ISSUE TITLE
字体模糊

### ISSUE THREAD

**Issue by korimas** [ying32/govcl#109]
除了窗口标题栏的文字，其他文字都有点模糊，分辨率的问题吗？
![image](https://user-images.githubusercontent.com/15672287/159120105-54f08978-b38e-407a-8ab2-8b542d213e7b.png)

**Comment by ying32** [comment]
参考[DPI相关](https://gitee.com/ying32/govcl/wikis/pages?sort_id=2242686&doc_id=102420)

**Comment by yhylovezl** [comment]
你好，TMiniWebview 在 ubuntu20.04 下使用有些问题。
安装libwebkitgtk-1.0可以正常使用，但是我不想使用1.0。
安装了 libwebkitgtk-3.0 不能正常使用，报错。
请问，是我安装的libwebkitgtk不对吗？
![1](https://user-images.githubusercontent.com/13374948/160069605-71260e92-8463-4f6a-a103-7eea080b49ee.jpg)
![2](https://user-images.githubusercontent.com/13374948/160069610-e3d3b3f0-c5fd-4886-94e6-d3b36e99a9e7.jpg)

**Comment by korimas** [comment]
多谢

> 参考[DPI相关](https://gitee.com/ying32/govcl/wikis/pages?sort_id=2242686&doc_id=102420)
