### ISSUE TITLE
Feature request: TMPlayerControl

### ISSUE THREAD

**Issue by lexesv** [ying32/govcl#11]
Hello!
It would be great if you implemented the component TMPlayerControl (with Linux & Windows support)
http://wiki.lazarus.freepascal.org/TMPlayerControl
https://sourceforge.net/p/lazarus-ccr/svn/HEAD/tree/components/mplayer/

**Comment by ying32** [comment]
Hi!
Currently, we do not consider introducing third-party components. If you only need to use audio media, you can consider using bass.dll. See the [mp3Player](https://github.com/ying32/govcl/tree/master/samples/mp3Player).

Thank you for your attention.

**Comment by lexesv** [comment]
Thanks, but I need TMPlayerControl for implement cross-platform IPTV player in GO.
Maybe there are some other ways?

**Comment by ying32** [comment]
If you are familiar with the pascal language, you can try to simply wrap the TMPlayerControl control and then compile it into the liblcl project.  Or try using the media library in go language.
