### ISSUE TITLE
关于Ubuntu20.04下使用TMiniWebview问题

### ISSUE THREAD

**Issue by yhylovezl** [ying32/govcl#110]
你好，TMiniWebview 在 ubuntu20.04 下使用有些问题。
安装libwebkitgtk-1.0可以正常使用，但是我不想使用1.0。
安装了 libwebkitgtk-3.0 不能正常使用，报错。
请问，是我安装的libwebkitgtk不对吗？
![1](https://user-images.githubusercontent.com/13374948/160069605-71260e92-8463-4f6a-a103-7eea080b49ee.jpg)
![2](https://user-images.githubusercontent.com/13374948/160069610-e3d3b3f0-c5fd-4886-94e6-d3b36e99a9e7.jpg)

**Comment by ying32** [comment]
liblcl是gtk2的，而libwebkitgtk-3.0需要gtk3支持…所以没办法。

**Comment by yhylovezl** [comment]
好的谢谢。
