### ISSUE TITLE
使用了最新的TCheckComboBox后，Application.Run会崩溃

### ISSUE THREAD

**Issue by lstarboy** [ying32/govcl#113]
使用了最新的TCheckComboBox后，并且重编liblcl后，运行Application.Run会崩溃（可通过最新的Basic Sample中打开(f *TMainForm) OnFormCreate 中的注释即可重现），感觉是liblcl的编译问题，能否提供最新版的二进制liblcl文件？

**Comment by ying32** [comment]
我大概率猜到你的问题应该是：[文档中重要提醒的第一条](https://gitee.com/ying32/govcl/wikis/pages?sort_id=2030600&doc_id=102420)
