### ISSUE TITLE
Can someone make a step by step guide how this can work on a mac?

### ISSUE THREAD

**Issue by MarcelXia** [ying32/govcl#115]

**Comment by ying32** [comment]
The step already exists in  [README.md](/ying32/govcl/blob/master/README.md) .

**Comment by MarcelXia** [comment]
well, I still have this:
vendor/github.com/ying32/govcl/vcl/api/importFuncsAuto.go:392:53: undefined: TMessage

**Comment by ying32** [comment]
MacOS M1？ 如果是的话，暂不支持，不过fork的项目重有人做了M1的支持。

**Comment by 3084fuid** [comment]
@ying32 谢谢你。我喜欢govcl! Will M1 support be merged in future? Are you still actively maintaining govcl?

**Comment by ying32** [comment]
@3084fuid The  [dev](https://github.com/ying32/govcl/tree/dev)  branch has been merged, but I can't provide the liblcl.dylib under M1 because I don't have the relevant device.

**Comment by 3084fuid** [comment]
Thank you very much for your answer. This does make sense.

**Comment by MarcelXia** [comment]
ld: warning: object file (/var/folders/2j/sl_kv1311vggqj0m8jy3_w7w0000gn/T/go-link-3362521056/000002.o) was built for newer macOS version (11.1) than being linked (11.0)
ld: warning: object file (/var/folders/2j/sl_kv1311vggqj0m8jy3_w7w0000gn/T/go-link-3362521056/000003.o) was built for newer macOS version (11.1) than being linked (11.0)
ld: warning: object file (/var/folders/2j/sl_kv1311vggqj0m8jy3_w7w0000gn/T/go-link-3362521056/000004.o) was built for newer macOS version (11.1) than being linked (11.0)
ld: warning: object file (/var/folders/2j/sl_kv1311vggqj0m8jy3_w7w0000gn/T/go-link-3362521056/000005.o) was built for newer macOS version (11.1) than being linked (11.0)
ld: warning: object file (/var/folders/2j/sl_kv1311vggqj0m8jy3_w7w0000gn/T/go-link-3362521056/000006.o) was built for newer macOS version (11.1) than being linked (11.0)
ld: warning: object file (/var/folders/2j/sl_kv1311vggqj0m8jy3_w7w0000gn/T/go-link-3362521056/000007.o) was built for newer macOS version (11.1) than being linked (11.0)
ld: warning: object file (/var/folders/2j/sl_kv1311vggqj0m8jy3_w7w0000gn/T/go-link-3362521056/000008.o) was built for newer macOS version (11.1) than being linked (11.0)
ld: warning: object file (/var/folders/2j/sl_kv1311vggqj0m8jy3_w7w0000gn/T/go-link-3362521056/000009.o) was built for newer macOS version (11.1) than being linked (11.0)
ld: warning: object file (/var/folders/2j/sl_kv1311vggqj0m8jy3_w7w0000gn/T/go-link-3362521056/000010.o) was built for newer macOS version (11.1) than being linked (11.0)
ld: warning: object file (/var/folders/2j/sl_kv1311vggqj0m8jy3_w7w0000gn/T/go-link-3362521056/000011.o) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/var/folders/2j/sl_kv1311vggqj0m8jy3_w7w0000gn/T/go-link-3362521056/000012.o) was built for newer macOS version (12.0) than being linked (11.0)
dlopen err: dlopen(/Users/marcelloh/data/go-private/WiMaLiCommander/liblcl.dylib, 0x0009): tried: '/Users/marcelloh/data/go-private/WiMaLiCommander/liblcl.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))
panic: dlopen("liblcl.dylib"), failed.

goroutine 1 [running]:
github.com/ying32/govcl/vcl/api.loadUILib()
        /Users/marcelloh/data/go-private/WiMaLiCommander/vendor/github.com/ying32/govcl/vcl/api/dylib_nonmemory.go:32 +0xe8
github.com/ying32/govcl/vcl/api.init()
        /Users/marcelloh/data/go-private/WiMaLiCommander/vendor/github.com/ying32/govcl/vcl/api/dylib.go:24 +0x14c
exit status 2

**Comment by ying32** [comment]
@MarcelXia I've said that I can't provide the arm version of liblcl.dylib.

**Comment by MarcelXia** [comment]
Why close this? I know you can't provide it, but perhaps an other person can. (You're not alone on this planet, right?)

**Comment by ying32** [comment]
In your question #102 I already told you that other people have compiled liblcl.dylib for arm under macOS, but you ignored this? Should I not close it?

**Comment by MarcelXia** [comment]
Because I don't ask for that, but for a step by step guide on how to do this :-(
I really want to try this package, but am not able to do this.
(all new Macs will have an M1 or M2, so you will miss a platform later on)

**Comment by ying32** [comment]
I also answered the steps before.
whatever!

**Comment by MarcelXia** [comment]
I'm sorry, but don't be rude.

So when I follow the steps (which I did), how come I have an error?
(I think there's something missing in the steps, or I am doing something wrong)
Let's assume, I do something wrong, how can I check what is wrong?
