### ISSUE TITLE
搞了一个晚上还卡在这...

### ISSUE THREAD

**Issue by bequt** [ying32/govcl#117]
![image](https://user-images.githubusercontent.com/16882457/162578063-89847e49-b1fa-4ba7-9cc9-660e26c9406b.png)

已经mod加导入库, 但是一直undefined..

**Comment by ying32** [comment]
没事多看看go的基础……   
`go build` 而不是 `go build main.go`。指定文件只会编译单个而不是编译整个包中所有文件
