### ISSUE TITLE
请教下，几个有Canvas的控件，有性能区别吗？

### ISSUE THREAD

**Issue by korimas** [ying32/govcl#121]
主要需求是绘制带颜色背景的文字，类似那种带语言高亮显示的文本编辑器，文字内容是会不停变动的，不知道选择哪个控件好，性能有没有差异。比如用paintbox

**Comment by ying32** [comment]
简单的随便都行呗，TPaintBox一般就用来绘制用

**Comment by korimas** [comment]
现在考虑整体用paintbox，一行用一个bitmap，paintbox一行一行的draw，上下滚动的时候，有些bitmap可以复用，挪动下位置就可以，不用滚动一点点就全部绘制刷新一遍，有什么更好的方案吗？

**Comment by ying32** [comment]
你这是要自己画一个文本编辑器么，如是我不建议你这么弄，当然你要厉害当我没说。。。

**Comment by korimas** [comment]
的确是...我理解下来，只要性能扛得住就可以

**Comment by ying32** [comment]
TRichEdit 就有这种功能，能给每个字设置不同的颜色和字体
