### ISSUE TITLE
系统托盘添加菜单,操作另外一个窗口时,会影响到主窗口

### ISSUE THREAD

**Issue by lyon-liang** [ying32/govcl#128]
我在系统托盘增加一个菜单,点击会显示一个窗口
当我关闭或者缩小显示的窗口时,主窗口也会跟着缩小
能设置窗口不影响吗

如果是直接创建就show的窗口,则不会影响主窗口

**Comment by ying32** [comment]
上代码，或者设置Form的ShowInTaskBar为stAlways

**Comment by lyon-liang** [comment]
![image](https://user-images.githubusercontent.com/35824397/169938017-9ff96886-4f2e-4e7c-9b18-795ed522f9f6.png)
![image](https://user-images.githubusercontent.com/35824397/169938725-a6bd0d83-389f-47ce-b93c-63e62a25a4ec.png)
如果关闭了右下角那个窗口,主窗口也跟着缩小了

**Comment by lyon-liang** [comment]
package screen

import (
	"devicePaser/logMessage"
	"devicePaser/util"
	"devicePaser/web"
	"fmt"
	"github.com/kbinani/screenshot"
	"github.com/ying32/govcl/vcl"
	"github.com/ying32/govcl/vcl/rtl"
	"github.com/ying32/govcl/vcl/types"
	"github.com/ying32/govcl/vcl/types/colors"
	"os/exec"
	"runtime"
	"strings"
	"time"
)

type TMainForm struct {
	*vcl.TForm
	toolBar *vcl.TToolBar
	Btn2    *vcl.TButton
}

type TShotForm struct {
	*vcl.TForm
	isMouseDown  bool
	isMouseMove  bool
	mouseDownPos types.TPoint
}

type TOrgForm struct {
	*vcl.TForm
	lblEditOrgCode  *vcl.TLabeledEdit
	lblEditDeptCode *vcl.TLabeledEdit
	lblEditIpAddr   *vcl.TLabeledEdit
	saveBtn         *vcl.TButton
}

var (
	mainForm   *TMainForm
	screenForm *TForm
	shotForm   *TShotForm
	orgForm    *TOrgForm
	shot       *Shot
)

func Run() {
	vcl.Application.Initialize()
	//窗口在任务栏
	vcl.Application.SetMainFormOnTaskBar(true)
	//配置窗口
	vcl.Application.CreateForm(&mainForm)
	//始终悬浮的出窗口
	vcl.Application.CreateForm(&shotForm)
	//隐藏的截图窗口
	vcl.Application.CreateForm(&screenForm)
	//机构科室配置窗口
	vcl.Application.CreateForm(&orgForm)
	//消息弹出框
	vcl.Application.CreateForm(&InfoDialog)
	vcl.Application.Icon().LoadFromFile("main.ico")
	/*-------mainForm-------*/
	mainForm.SetCaption("小型设备解析器")
	mainForm.SetOnClose(mainForm.onClose)
	mainForm.ScreenCenter()
	mainForm.toolBar = vcl.NewToolBar(mainForm)
	mainForm.toolBar.SetCaption("toolBar")
	mainForm.toolBar.SetParent(mainForm)
	mainForm.Btn2 = vcl.NewButton(mainForm.toolBar)
	mainForm.Btn2.SetCaption("配置截图")
	mainForm.Btn2.SetParent(mainForm.toolBar)
	mainForm.Btn2.SetOnClick(mainForm.onBtn2Click)

	//悬浮窗口配置
	//始终在最前面
	shotForm.SetFormStyle(types.FsSystemStayOnTop)
	//最大化最小化关闭按钮隐藏
	shotForm.SetBorderIcons(types.FdAnsiOnly)
	//去掉标题栏
	shotForm.SetBorderStyle(types.BsNone)
	shotForm.SetWidth(66)
	shotForm.SetHeight(30)
	shotForm.SetLeft(util.ShotFormLeft)
	shotForm.SetTop(util.ShotFormTop)
	shotForm.SetBorderWidth(types.None)
	shotForm.SetOnMouseDown(shotForm.OnLblCaptionMouseDown)
	shotForm.SetOnMouseMove(shotForm.OnLblCaptionMouseMove)
	shotForm.SetOnMouseEnter(shotForm.OnLblCaptionMouseEnter)
	shotForm.SetOnMouseUp(shotForm.OnLblCaptionMouseUp)
	shotForm.SetOnClick(shotForm.onBtn1Click)
	shotForm.SetOnPaint(shotForm.OnFormPaint)
	shotForm.SetWindowState(types.WsNormal)
	shotForm.Show()

	/*-------screenForm-------*/
	screenForm.Initialize()
	screenForm.OnExit = func() {
		mainForm.SetWindowState(types.WsNormal)
	}
	//消息弹出框初始化
	InitMessage()
	//自动截图弹出
	popupShotMenu()
	//配置截图弹出
	popupMainMenu()
	//系统托盘
	initTrayIcon()
	//消息弹出
	initConfig()
	//gin启动
	go web.Run()
	vcl.Application.Run()
}

func (f *TShotForm) OnFormPaint(sender vcl.IObject) {
	pngImg := vcl.NewPngImage()
	stream := vcl.NewMemoryStreamFromBytes(util.ReadFileByte("shot.png"))
	stream.SetPosition(0)
	pngImg.LoadFromStream(stream)
	f.Canvas().Draw(0, 0, pngImg)
	stream.Free()
	pngImg.Free()
}

func initTrayIcon() {
	//系统托盘
	trayIcon := vcl.NewTrayIcon(mainForm)
	pm := vcl.NewPopupMenu(mainForm)
	item := vcl.NewMenuItem(mainForm)
	item.SetCaption("显示(&S)")
	item.SetOnClick(func(vcl.IObject) {
		mainForm.Show()
		//Windows上为了最前面显示，有时候要调用SetForegroundWindow
		rtl.SetForegroundWindow(mainForm.Handle())
		vcl.Application.Restore()
		vcl.Application.BringToFront()
	})
	pm.Items().Add(item)

	orgItem := vcl.NewMenuItem(mainForm)
	orgItem.SetCaption("机构配置(&S)")
	orgItem.SetOnClick(func(vcl.IObject) {
		orgForm.Show()
	})
	pm.Items().Add(orgItem)

	item = vcl.NewMenuItem(mainForm)
	item.SetCaption("退出(&E)")
	item.SetOnClick(func(vcl.IObject) {
		// 主窗口关闭
		rememberFormCoordinate()
		mainForm.Close()
	})
	pm.Items().Add(item)
	trayIcon.SetPopupMenu(pm)
	trayIcon.SetHint(mainForm.Caption())
	trayIcon.SetVisible(true)

	// 捕捉最小化
	vcl.Application.SetOnMinimize(func(sender vcl.IObject) {
		// 主窗口隐藏掉
		mainForm.Hide()
		//截图窗口一直显示
		shotForm.Show()
	})
}

func popupMainMenu() {
	var flag = false
	item := vcl.NewMenuItem(mainForm)
	pm := vcl.NewPopupMenu(mainForm)
	for i := 0; i < len(util.AloConfig.InspectionTypeList); i++ {
		if i >= 1 {
			flag = true
		}
		mm := util.AloConfig.InspectionTypeList[i]
		item = vcl.NewMenuItem(mainForm)
		item.SetCaption(mm.Inspection)
		item.SetOnClick(func(vcl.IObject) {
			if mm.IsMultiple {
				return
			}
			util.CurrentType = mm.Inspection
			util.CurrentMultiple = mm.IsMultiple
			if confirmShot() {
				mainForm.SetWindowState(types.WsMinimized)
				screenForm.Open()
			}
		})

		if mm.IsMultiple {
			for j := 0; j < len(mm.ImgCode); j++ {
				subItem := vcl.NewMenuItem(mainForm)
				code := mm.ImgCode[j]
				subItem.SetCaption(code)
				subItem.SetOnClick(func(vcl.IObject) {
					util.CurrentType = mm.Inspection
					util.CurrentMultiple = mm.IsMultiple
					util.CurrentSmallType = code
					mainForm.SetWindowState(types.WsMinimized)
					screenForm.Open()
				})
				item.Add(subItem)
			}
		}

		pm.Items().Add(item)
	}
	if flag {
		// 将窗口设置一个弹出菜单，右键单击就可显示
		mainForm.SetPopupMenu(pm)
	}
}

func popupShotMenu() {
	var flag = false
	item := vcl.NewMenuItem(shotForm)
	pm := vcl.NewPopupMenu(shotForm)
	for i := 0; i < len(util.AloConfig.InspectionTypeList); i++ {
		if i >= 1 {
			flag = true
		}
		mm := util.AloConfig.InspectionTypeList[i]
		item = vcl.NewMenuItem(shotForm)
		item.SetCaption(mm.Inspection)
		item.SetOnClick(func(vcl.IObject) {
			if mm.IsMultiple {
				return
			}
			util.CurrentType = mm.Inspection
			util.CurrentMultiple = mm.IsMultiple
			if !isShotConfig() {
				return
			}
			mainForm.SetWindowState(types.WsMinimized)
			screenShot(util.AloConfig.Coordinate[util.CurrentType])
		})

		if mm.IsMultiple {
			for j := 0; j < len(mm.ImgCode); j++ {
				code := mm.ImgCode[j]
				subItem := vcl.NewMenuItem(mainForm)
				subItem.SetCaption(code)
				subItem.SetOnClick(func(vcl.IObject) {
					util.CurrentType = mm.Inspection
					util.CurrentMultiple = mm.IsMultiple
					util.CurrentSmallType = code
					if !isShotConfig() {
						return
					}
					mainForm.SetWindowState(types.WsMinimized)
					screenShot(util.AloConfig.Coordinate[util.CurrentType])
				})
				item.Add(subItem)
			}
		}
		pm.Items().Add(item)
	}
	if flag {
		// 将窗口设置一个弹出菜单，右键单击就可显示
		shotForm.SetPopupMenu(pm)
	}

}

func initConfig() {

	mm := vcl.NewMainMenu(mainForm)
	btnConfig := vcl.NewMenuItem(mainForm)
	btnConfig.SetCaption("配置")
	//btnConfig.SetOnClick(importClick)
	mm.Items().Add(btnConfig)
	//
	btnImport := vcl.NewMenuItem(mainForm)
	btnImport.SetCaption("导入")
	btnConfig.Add(btnImport)
	btnImport.SetOnClick(importClick)

	btnHtml := vcl.NewMenuItem(mainForm)
	btnHtml.SetCaption("页面")
	btnConfig.Add(btnHtml)
	btnHtml.SetOnClick(htmlClick)

	btnServer := vcl.NewMenuItem(mainForm)
	btnServer.SetCaption("服务")
	mm.Items().Add(btnServer)

	btnRun := vcl.NewMenuItem(mainForm)
	btnRun.SetCaption("启动")
	btnServer.Add(btnRun)
	btnRun.SetOnClick(runClick)

	btnStop := vcl.NewMenuItem(mainForm)
	btnStop.SetCaption("停止")
	btnServer.Add(btnStop)
	btnStop.SetOnClick(stopClick)

	page := vcl.NewPageControl(mainForm)
	page.SetParent(mainForm)
	page.SetAlign(types.AlClient)
	tabConsole := vcl.NewTabSheet(mainForm)
	tabConsole.SetParent(page)
	tabConsole.SetCaption("日志")
	console := vcl.NewMemo(mainForm)
	console.SetParent(tabConsole)
	console.SetAlign(types.AlClient)
	consoleFont := vcl.NewFont()
	consoleFont.SetColor(colors.ClBlue)
	console.SetFont(consoleFont)
	console.SetScrollBars(types.SsAutoBoth)
	go func() {
		for true {
			select {
			case m := <-logMessage.LogChan:
				console.Append(m)
			}
		}
	}()
}

func (f *TShotForm) OnLblCaptionMouseUp(sender vcl.IObject, button types.TMouseButton, shift types.TShiftState, x, y int32) {
	f.isMouseDown = false
	f.isMouseMove = false
}

func (f *TShotForm) OnLblCaptionMouseDown(sender vcl.IObject, button types.TMouseButton, shift types.TShiftState, x, y int32) {
	if button == types.MbLeft {
		f.isMouseDown = true
		f.mouseDownPos.X = x
		f.mouseDownPos.Y = y
	}
}

func (f *TShotForm) OnLblCaptionMouseMove(sender vcl.IObject, shift types.TShiftState, x, y int32) {
	if f.isMouseDown {
		f.isMouseMove = true
		f.SetLeft(f.Left() + (x - f.mouseDownPos.X))
		f.SetTop(f.Top() + (y - f.mouseDownPos.Y))
	}
}

func (f *TShotForm) OnLblCaptionMouseEnter(sender vcl.IObject) {
	f.SetCursor(types.SoBeginning)
}

func (f *TMainForm) onClose(sender vcl.IObject, action *types.TCloseAction) {
	rememberFormCoordinate()
	vcl.Application.ExceptionExitCode()
}

func (f *TShotForm) onBtn1Click(sender vcl.IObject) {
	if f.isMouseDown && f.isMouseMove {
		return
	}
	hasConfig()
	//有两种以上的图片类型要弹宽
	if len(util.AloConfig.InspectionTypeList) > 1 {
		f.PopupMenu().Popup2()
	} else {
		if !isShotConfig() {
			return
		}
	}

	if (util.CurrentType != "" || util.CurrentSmallType != "") && len(util.AloConfig.InspectionTypeList) == 1 && len(util.ImgCodeList[util.CurrentType]) > 0 {
		mainForm.SetWindowState(types.WsMinimized)
		screenShot(util.AloConfig.Coordinate[util.CurrentType])
	}

}

func (f *TOrgForm) OnFormCreate(sender vcl.IObject) {
	f.SetCaption("机构配置")
	f.EnabledMaximize(false)
	f.SetWidth(300)
	f.SetHeight(110)
	f.ScreenCenter()
	f.SetBorderIcons(types.FdTrueTypeOnly)
	f.SetOnClose(f.closeConfig)
	f.lblEditOrgCode = vcl.NewLabeledEdit(f)
	f.lblEditOrgCode.SetParent(f)
	f.lblEditOrgCode.SetLeft(60)
	f.lblEditOrgCode.SetTop(10)
	f.lblEditOrgCode.SetLabelPosition(types.LpLeft)
	f.lblEditOrgCode.SetLabelSpacing(6)
	f.lblEditOrgCode.EditLabel().SetCaption("机构编码:")
	f.lblEditOrgCode.SetText(util.AloConfig.OrgCode)

	f.lblEditDeptCode = vcl.NewLabeledEdit(f)
	f.lblEditDeptCode.SetParent(f)
	f.lblEditDeptCode.SetLeft(200)
	f.lblEditDeptCode.SetTop(10)
	f.lblEditDeptCode.SetLabelPosition(types.LpLeft)
	f.lblEditDeptCode.SetLabelSpacing(6)
	f.lblEditDeptCode.EditLabel().SetCaption("科室编码:")
	f.lblEditDeptCode.SetText(util.AloConfig.DeptCode)

	f.lblEditIpAddr = vcl.NewLabeledEdit(f)
	f.lblEditIpAddr.SetParent(f)
	f.lblEditIpAddr.SetLeft(80)
	f.lblEditIpAddr.SetTop(45)
	f.lblEditIpAddr.SetWidth(f.Width() - f.lblEditIpAddr.Width() - 20)
	f.lblEditIpAddr.SetLabelPosition(types.LpLeft) // 默认
	f.lblEditIpAddr.SetLabelSpacing(12)
	f.lblEditIpAddr.EditLabel().SetCaption("前置机地址:")
	f.lblEditIpAddr.SetText(util.AloConfig.IpAddr)

	f.saveBtn = vcl.NewButton(f)
	f.saveBtn.SetParent(f)
	f.saveBtn.SetCaption("保存")
	f.saveBtn.SetLeft(120)
	f.saveBtn.SetTop(80)
	f.saveBtn.SetOnClick(f.saveOrgConfig)
}

func (f *TOrgForm) saveOrgConfig(sender vcl.IObject) {
	orgCode := f.lblEditOrgCode.Text()
	deptCode := f.lblEditDeptCode.Text()
	ipAddr := f.lblEditIpAddr.Text()

	if orgCode == "" {
		ShowError("机构编码不能为空")
		return
	} else if deptCode == "" {
		ShowError("科室编码不能为空")
		return
	} else if ipAddr == "" {
		ShowError("前置机地址不能为空")
		return
	}

	var str = ""
	s1 := "alo.orgCode="
	s2 := "alo.deptCode="
	s3 := "alo.ipAddr="

	if util.IsExist(util.ConfigFileName) {
		line := util.ReadLine(util.ConfigFileName)
		for i := 0; i < len(line); i++ {
			if !strings.Contains(line[i], s1) && !strings.Contains(line[i], s2) && !strings.Contains(line[i], s3) {
				str += line[i] + "\r"
			}
		}
	}

	str += s1 + orgCode + "\r"
	str += s2 + deptCode + "\r"
	str += s3 + ipAddr + "\r"
	util.WriteStringToFile(util.ConfigFileName, str)
	util.AloConfig.OrgCode = orgCode
	util.AloConfig.DeptCode = deptCode
	util.AloConfig.IpAddr = ipAddr
	defer f.Close()
}

func (f *TOrgForm) closeConfig(sender vcl.IObject, action *types.TCloseAction) {

}

//截图
func screenShot(coordinateList map[string]util.Coordinate) {
	//解决缩小窗口不及时,被截图窗口捕捉到
	t := time.After(100 * time.Millisecond)
	_, _ = <-t

	if util.CurrentMultiple {
		img, err := screenshot.Capture(coordinateList[util.CurrentSmallType].X, coordinateList[util.CurrentSmallType].Y, coordinateList[util.CurrentSmallType].W, coordinateList[util.CurrentSmallType].H)
		util.HandleError(err)
		util.SaveImg(util.CurrentSmallType, img)
		return
	}

	for key, coordinate := range coordinateList {
		img, err := screenshot.Capture(coordinate.X, coordinate.Y, coordinate.W, coordinate.H)
		util.HandleError(err)
		util.SaveImg(key, img)
	}

	//保存玩图片,设置当前类型为空
	if len(util.AloConfig.InspectionTypeList) > 1 {
		util.CurrentType = ""
		util.CurrentSmallType = ""
		util.CurrentMultiple = false
	}

}

func (f *TMainForm) onBtn2Click(sender vcl.IObject) {
	hasConfig()
	//有两种以上的图片类型要弹宽
	if len(util.AloConfig.InspectionTypeList) > 1 {
		f.PopupMenu().Popup2()
	}
	if util.CurrentType != "" && len(util.AloConfig.InspectionTypeList) == 1 && len(util.ImgCodeList[util.CurrentType]) > 0 {
		mainForm.SetWindowState(types.WsMinimized)
		screenForm.Open()
	} else {
		vcl.ShowMessage("该检查没有配置图片类型")
	}

}

func importClick(sender vcl.IObject) {
	dlgOpen := vcl.NewOpenDialog(mainForm)
	dlgOpen.SetFilter("文本文件(*.txt)|*.txt|所有文件(*.*)|*.*")
	dlgOpen.SetOnClose(func(sender vcl.IObject) {
		if dlgOpen.FileName() != "" {
			util.LoadConfig(dlgOpen.FileName())
			util.MoveFile(dlgOpen.FileName(), util.ConfigFileName)
		}
	})
	dlgOpen.SetOptions(dlgOpen.Options().Include(types.OfShowHelp, types.OfAllowMultiSelect)) //rtl.Include(, types.OfShowHelp))
	dlgOpen.SetTitle("打开")
	dlgOpen.Execute()
}

func htmlClick(sender vcl.IObject) {

	var cmd string
	var args []string

	switch runtime.GOOS {
	case "windows":
		cmd = "cmd"
		args = []string{"/c", "start"}
	case "darwin":
		cmd = "open"
	default: // "linux", "freebsd", "openbsd", "netbsd"
		cmd = "xdg-open"
	}
	if util.AloConfig.OrgCode == "" {
		orgForm.Show()
		return
	}
	args = append(args, "http://localhost:"+util.AloConfig.Port+"/index")
	err1 := exec.Command(cmd, args...).Start()
	util.HandleError(err1)
}

func runClick(sender vcl.IObject) {
	if web.Server == nil {
		go web.Run()
		util.LoadConfig(util.ConfigFileName)
	} else {
		ShowError("服务已启动")
	}
}

func stopClick(sender vcl.IObject) {
	if web.Server == nil {
		ShowError("服务已停止")
	} else {
		go web.Stop()
	}
}

func hasConfig() {
	if util.AloConfig.DeviceName == "" && util.AloConfig.SavePath == "" && util.AloConfig.ImgPath == "" && util.AloConfig.FilePath == "" {
		vcl.ShowMessage("请先通过页面或者导入配置文件")
	}
}
func rememberFormCoordinate() {
	if shotForm.Top() == util.ShotFormTop && shotForm.Left() == util.ShotFormLeft {
		return
	}
	var str string
	s1 := "shotForm.left="
	s2 := "shotForm.top="
	//读取行
	line := util.ReadLine(util.ConfigFileName)
	for i := 0; i < len(line); i++ {
		if !strings.Contains(line[i], s1) && !strings.Contains(line[i], s2) {
			str += line[i] + "\r"
		}
	}
	//跟源文件拼接
	str += "shotForm.left=" + fmt.Sprint(shotForm.Left()) + "\r"
	str += "shotForm.top=" + fmt.Sprint(shotForm.Top()) + "\r"

	util.OpenFileWriteString(util.ConfigFileName, str)
}

**Comment by lyon-liang** [comment]
package main

import (
	"fmt"
	"runtime"

	_ "github.com/ying32/govcl/pkgs/winappres"
	"github.com/ying32/govcl/vcl"
	"github.com/ying32/govcl/vcl/types"
	//"github.com/ying32/govcl/vcl/rtl"
)

var orgForm *TOrgForm

type TOrgForm struct {
	*vcl.TForm
	lblEditOrgCode  *vcl.TLabeledEdit
	lblEditDeptCode *vcl.TLabeledEdit
	lblEditIpAddr   *vcl.TLabeledEdit
	saveBtn         *vcl.TButton
}

func main() {

	vcl.Application.Initialize()
	vcl.Application.SetMainFormOnTaskBar(true)

	mainForm := vcl.Application.CreateForm()
	vcl.Application.CreateForm(&orgForm)

	mainForm.SetCaption("Hello")
	mainForm.SetPosition(types.PoScreenCenter)
	vcl.Application.Icon().LoadFromFile("main.ico")
	mMenu := vcl.NewMainMenu(mainForm)
	mmItem := vcl.NewMenuItem(mainForm)
	mmItem.SetCaption("File")
	mMenu.Items().Add(mmItem)

	trayicon := vcl.NewTrayIcon(mainForm)

	btn := vcl.NewButton(mainForm)
	btn.SetParent(mainForm)
	btn.SetCaption("ShowBalloon")
	btn.SetLeft(20)
	btn.SetTop(30)
	btn.SetWidth(100)
	btn.SetOnClick(func(vcl.IObject) {
		trayicon.SetBalloonTitle("test")
		trayicon.SetBalloonTimeout(1000)
		trayicon.SetBalloonHint("我是提示正文啦")
		trayicon.ShowBalloonHint()
	})

	pm := vcl.NewPopupMenu(mainForm)
	item := vcl.NewMenuItem(mainForm)
	item.SetCaption("显示(&S)")
	item.SetOnClick(func(vcl.IObject) {

		mainForm.Show()
		// Windows上为了最前面显示，有时候要调用SetForegroundWindow
		//rtl.SetForegroundWindow(mainForm.Handle())
		//vcl.Application.Restore()
		//vcl.Application.BringToFront()
	})
	pm.Items().Add(item)

	configItem := vcl.NewMenuItem(orgForm)
	configItem.SetCaption("机构配置(&S)")
	configItem.SetOnClick(func(vcl.IObject) {
		orgForm.Show()
	})
	pm.Items().Add(configItem)

	item = vcl.NewMenuItem(mainForm)
	item.SetCaption("退出(&E)")
	item.SetOnClick(func(vcl.IObject) {
		// 主窗口关闭
		mainForm.Close()
		// 或者使用
		//		vcl.Application.Terminate()
	})
	pm.Items().Add(item)
	trayicon.SetPopupMenu(pm)
	// lcl库得手指定，在windows下，如果实例资源中存在一个名为 MAINICON 的图标资源，则会自动加载，下面只是应对于linux与macOS下

	if runtime.GOOS != "windows" {
		// 这是使用文件加载方法，不考虑外部文件的话，可以用新的内存方法加载
		//icon := vcl.NewIcon()
		//icon.LoadFromFile(rtl.ExtractFilePath(vcl.Application.ExeName()) + "/2.ico")
		//trayicon.SetIcon(icon)
		//icon.Free()
		// 将图标应用到Application中的Icon中，到时候随时可以使用
		// 但也可不使用
		//loadMainIconFromStream(vcl.Application.Icon())
		//loadMainIconFromStream(trayicon.Icon())

	} else {
		trayicon.SetIcon(vcl.Application.Icon())
	}

	trayicon.SetHint(mainForm.Caption())
	trayicon.SetVisible(true)

	// 捕捉最小化
	vcl.Application.SetOnMinimize(func(sender vcl.IObject) {
		mainForm.Hide() // 主窗口最隐藏掉
	})

	// 这里写啥好呢，macOS下似乎这些事件跟PopupMenu有冲突
	if runtime.GOOS != "darwin" {
		trayicon.SetOnDblClick(func(vcl.IObject) {
			// macOS似乎不支持双击
			trayicon.SetBalloonTitle("test")
			trayicon.SetBalloonTimeout(10000)
			trayicon.SetBalloonHint("我是提示正文啦")
			trayicon.ShowBalloonHint()
			fmt.Println("TrayIcon DClick.")
		})
	}
	vcl.Application.Run()
}

// 主要是用于linux跟macOS下，因为不能像Windows一样直接内置到资源中
func loadMainIconFromStream(outIcon *vcl.TIcon) {
	if outIcon.IsValid() {
		//mem := vcl.NewMemoryStreamFromBytes(mainIconBytes)
		//defer mem.Free() // 不要在阻塞的时候使用defer不然会一直到阻塞结束才释放，这里使用是因为这个函数结束了就释放了
		//mem.SetPosition(0)
		//outIcon.LoadFromStream(mem)
		//outIcon.LoadFromBytes(mainIconBytes)
	}
}

func (f *TOrgForm) OnFormCreate(sender vcl.IObject) {
	f.SetCaption("Hello")
	f.EnabledMaximize(false)
	f.SetWidth(300)
	f.SetHeight(110)
	f.ScreenCenter()
	f.SetBorderIcons(types.FdTrueTypeOnly)
	f.lblEditOrgCode = vcl.NewLabeledEdit(f)
	f.lblEditOrgCode.SetParent(f)
	f.lblEditOrgCode.SetLeft(60)
	f.lblEditOrgCode.SetTop(10)
	f.lblEditOrgCode.SetLabelPosition(types.LpLeft)
	f.lblEditOrgCode.SetLabelSpacing(6)
	f.lblEditOrgCode.EditLabel().SetCaption("机构编码:")
	f.lblEditOrgCode.SetText("util.AloConfig.OrgCode")

	f.lblEditDeptCode = vcl.NewLabeledEdit(f)
	f.lblEditDeptCode.SetParent(f)
	f.lblEditDeptCode.SetLeft(200)
	f.lblEditDeptCode.SetTop(10)
	f.lblEditDeptCode.SetLabelPosition(types.LpLeft)
	f.lblEditDeptCode.SetLabelSpacing(6)
	f.lblEditDeptCode.EditLabel().SetCaption("科室编码:")
	f.lblEditDeptCode.SetText("util.AloConfig.DeptCode")

	f.lblEditIpAddr = vcl.NewLabeledEdit(f)
	f.lblEditIpAddr.SetParent(f)
	f.lblEditIpAddr.SetLeft(80)
	f.lblEditIpAddr.SetTop(45)
	f.lblEditIpAddr.SetWidth(f.Width() - f.lblEditIpAddr.Width() - 20)
	f.lblEditIpAddr.SetLabelPosition(types.LpLeft) // 默认
	f.lblEditIpAddr.SetLabelSpacing(12)
	f.lblEditIpAddr.EditLabel().SetCaption("前置机地址:")
	f.lblEditIpAddr.SetText("util.AloConfig.IpAddr")

	f.saveBtn = vcl.NewButton(f)
	f.saveBtn.SetParent(f)
	f.saveBtn.SetCaption("保存")
	f.saveBtn.SetLeft(120)
	f.saveBtn.SetTop(80)
}

**Comment by ying32** [comment]
```go
orgForm.SetShowInTaskBar(types.StAlways)
```

**Comment by lyon-liang** [comment]
可以了,感谢
