### ISSUE TITLE
列表单元格添加进度条和按钮

### ISSUE THREAD

**Issue by chenhl05** [ying32/govcl#129]
大佬好，请教三个问题：

1）能否在 TListView 列表中添加 TProgressBar 进度条呢？我看到 samples 中的 listviewadvcustomdraw 是使用 canvas 的方式实现，觉得 canvas 样式没有 TProgressBar 好看。

2）TListView 的单元格中，能否添加按钮组件呢？

3）samples/stringgrid2 示例，每列能像 TListView 那样拖拉宽度吗？

**Comment by ying32** [comment]
1、不建议直接用进度条，用不好一来内存泄露，二来卡顿严重，canvas的你想画啥就画啥样的，取决于你的技术。
2、TlistView中也可以，跟第1点一样。
3、TStringGrid的Options中有goColSizing，这个可以控制列可调，用法可以见例子里的。

**Comment by chenhl05** [comment]
TlistView  鼠标点击的单元格，可以判断是第几列吗？

在 listviewCommon.go:

```
    lv.SetOnClick(func(sender vcl.IObject) {
        sel := vcl.AsListView(sender).Selected()
        if sel.IsValid() {
            fmt.Println("select, index:", sel.Index(), ", caption:", sel.Caption(), ", data:", sel.Data())
        }
    })
```

sel.Index() 只能确定是第几行。

**Comment by ying32** [comment]
你即然看过那个自绘进度条的了，那里面不就有么，不然怎么玩
