### ISSUE TITLE
*TComboBox 下拉框怎么失去焦点，不让进去编辑，怎么取消选中的文字

### ISSUE THREAD

**Issue by jiangchengcai** [ying32/govcl#130]
![image](https://user-images.githubusercontent.com/43169504/170914360-fe66fcf5-2e41-45bb-9a7c-d0ccdc2c36fd.png)

**Comment by ying32** [comment]
不可编辑属性有ReadOnly看名字就知道，
进入退出事件有OnEnter和OnExit。

**Comment by jiangchengcai** [comment]
TComboBox 是没有ReadOnly的属性
SetSelLength和SetSelStart 这两个属性只有初始化的时候没有选中文字、重新选中下拉框没有效果

**Comment by jiangchengcai** [comment]
![image](https://user-images.githubusercontent.com/43169504/171126460-dc26ae05-a412-44c4-a994-8e6a2b239af0.png)

**Comment by ying32** [comment]
1、看了下设计器中有这个属性，代码中没有，准备补个。
2、如果没办法取消选择的话，那我也不知道了。
