### ISSUE TITLE
 go install github.com/ying32/govcl@latest 安装失败

### ISSUE THREAD

**Issue by luckrill** [ying32/govcl#133]
自己的go版本 go version go1.18.3 windows/amd64
go get -u github.com/ying32/govcl
这个方式已经被废弃

使用这个方式，失败
 go install github.com/ying32/govcl@latest 

![image](https://user-images.githubusercontent.com/5372899/174467787-d0f89e1c-9d5f-4319-b497-7c3328d57ae3.png)

**Comment by ying32** [comment]
这个貌似无能为力，要么就用go.mod来做，要么就只能自己git clone下了

**Comment by luckrill** [comment]
自己还是没有入门，不知道如何运行 你开发的那么多 examples

**Comment by luckrill** [comment]
我现在开始调查 lazarus 
遇到 dialog 窗口，按钮都是 英文
我是 中文 windows10的环境，为什么不能显示 中文按钮
![image](https://user-images.githubusercontent.com/5372899/175471058-1d034ff4-04d8-40bf-81ee-3aae335b776d.png)

具体看这里
https://forum.lazarus.freepascal.org/index.php/topic,59708.0.html
