### ISSUE TITLE
只要窗口代码不放到main包下就出现: Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by BigCatGit** [ying32/govcl#135]
只要窗口代码不放到main包下就出现以下问题, windows和mac都出现了
Undefined symbols for architecture x86_64:
  "std::__1::__vector_base_common<true>::__throw_length_error() const", referenced from:

**Comment by ying32** [comment]
没碰到过这种情况。。。你这信息也太少了，而且看着像是gcc那块。。。

**Comment by BigCatGit** [comment]
Build Error: go build -o /Users/bigcat/Documents/Github/Test/__debug_bin -gcflags all=-N -l .
#
/usr/local/go/pkg/tool/darwin_amd64/link: running clang++ failed: exit status 1
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000002.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000003.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000004.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000005.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000006.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000007.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000008.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000009.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000010.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000011.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000012.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000013.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000014.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000015.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000016.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000017.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000018.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000019.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000020.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000021.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000022.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000023.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000024.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000025.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000026.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000027.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000028.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000029.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000030.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000031.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000032.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000033.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000034.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000035.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000036.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000037.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000038.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000039.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000040.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000041.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000042.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000043.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000044.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000045.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000046.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000047.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000048.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000049.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000050.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000051.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000052.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000053.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000054.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000055.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000056.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000057.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000058.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000059.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000060.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000061.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000062.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000063.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000064.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000065.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/var/folders/sp/qktwd0pn1nl7cv2_klqn_nk40000gn/T/go-link-1576230756/000066.o) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/lib/libz.dylib) was built for newer macOS version (10.15) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_gapi.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_stitching.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_alphamat.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_aruco.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_barcode.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_bgsegm.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_bioinspired.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_ccalib.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_dnn_objdetect.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_dnn_superres.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_dpm.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_face.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_freetype.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_fuzzy.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_hfs.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_img_hash.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_intensity_transform.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_line_descriptor.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_mcc.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_quality.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_rapid.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_reg.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_rgbd.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_saliency.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_sfm.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_stereo.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_structured_light.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_phase_unwrapping.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_superres.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_optflow.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_surface_matching.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_tracking.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_highgui.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_datasets.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_text.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_plot.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_videostab.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_videoio.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_viz.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_wechat_qrcode.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_xfeatures2d.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_shape.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_ml.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_ximgproc.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_video.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_xobjdetect.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_objdetect.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_calib3d.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_imgcodecs.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_features2d.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_dnn.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_flann.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_xphoto.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_photo.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_imgproc.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: dylib (/usr/local/opt/opencv/lib/libopencv_core.dylib) was built for newer macOS version (12.0) than being linked (10.8)
ld: warning: object file (/Users/bigcat/Documents/Golang/pkg/mod/github.com/go-vgo/robotgo@v0.100.10/cdeps/mac/amd/libpng.a(png.o)) was built for newer macOS version (10.10) than being linked (10.8)
ld: warning: object file (/Users/bigcat/Documents/Golang/pkg/mod/github.com/go-vgo/robotgo@v0.100.10/cdeps/mac/amd/libpng.a(pngread.o)) was built for newer macOS version (10.10) than being linked (10.8)
ld: warning: object file (/Users/bigcat/Documents/Golang/pkg/mod/github.com/go-vgo/robotgo@v0.100.10/cdeps/mac/amd/libpng.a(pngwrite.o)) was built for newer macOS version (10.10) than being linked (10.8)
ld: warning: object file (/Users/bigcat/Documents/Golang/pkg/mod/github.com/go-vgo/robotgo@v0.100.10/cdeps/mac/amd/libpng.a(pngmem.o)) was built for newer macOS version (10.10) than being linked (10.8)
ld: warning: object file (/Users/bigcat/Documents/Golang/pkg/mod/github.com/go-vgo/robotgo@v0.100.10/cdeps/mac/amd/libpng.a(pngget.o)) was built for newer macOS version (10.10) than being linked (10.8)
ld: warning: object file (/Users/bigcat/Documents/Golang/pkg/mod/github.com/go-vgo/robotgo@v0.100.10/cdeps/mac/amd/libpng.a(pngset.o)) was built for newer macOS version (10.10) than being linked (10.8)
ld: warning: object file (/Users/bigcat/Documents/Golang/pkg/mod/github.com/go-vgo/robotgo@v0.100.10/cdeps/mac/amd/libpng.a(pngtrans.o)) was built for newer macOS version (10.10) than being linked (10.8)
ld: warning: object file (/Users/bigcat/Documents/Golang/pkg/mod/github.com/go-vgo/robotgo@v0.100.10/cdeps/mac/amd/libpng.a(pngrtran.o)) was built for newer macOS version (10.10) than being linked (10.8)
ld: warning: object file (/Users/bigcat/Documents/Golang/pkg/mod/github.com/go-vgo/robotgo@v0.100.10/cdeps/mac/amd/libpng.a(pngerror.o)) was built for newer macOS version (10.10) than being linked (10.8)
ld: warning: object file (/Users/bigcat/Documents/Golang/pkg/mod/github.com/go-vgo/robotgo@v0.100.10/cdeps/mac/amd/libpng.a(pngwio.o)) was built for newer macOS version (10.10) than being linked (10.8)
ld: warning: object file (/Users/bigcat/Documents/Golang/pkg/mod/github.com/go-vgo/robotgo@v0.100.10/cdeps/mac/amd/libpng.a(pngrutil.o)) was built for newer macOS version (10.10) than being linked (10.8)
ld: warning: object file (/Users/bigcat/Documents/Golang/pkg/mod/github.com/go-vgo/robotgo@v0.100.10/cdeps/mac/amd/libpng.a(pngwutil.o)) was built for newer macOS version (10.10) than being linked (10.8)
ld: warning: object file (/Users/bigcat/Documents/Golang/pkg/mod/github.com/go-vgo/robotgo@v0.100.10/cdeps/mac/amd/libpng.a(pngwtran.o)) was built for newer macOS version (10.10) than being linked (10.8)
ld: warning: object file (/Users/bigcat/Documents/Golang/pkg/mod/github.com/go-vgo/robotgo@v0.100.10/cdeps/mac/amd/libpng.a(pngrio.o)) was built for newer macOS version (10.10) than being linked (10.8)
Undefined symbols for architecture x86_64:
  "std::__1::__vector_base_common<true>::__throw_length_error() const", referenced from:
      std::__1::__vector_base<int, std::__1::allocator<int> >::__throw_length_error() const in 000024.o
      std::__1::__vector_base<cv::Mat, std::__1::allocator<cv::Mat> >::__throw_length_error() const in 000024.o
      std::__1::__vector_base<cv::Point_<int>, std::__1::allocator<cv::Point_<int> > >::__throw_length_error() const in 000024.o
      std::__1::__vector_base<std::__1::vector<cv::Point_<int>, std::__1::allocator<cv::Point_<int> > >, std::__1::allocator<std::__1::vector<cv::Point_<int>, std::__1::allocator<cv::Point_<int> > > > >::__throw_length_error() const in 000024.o
      std::__1::__vector_base<cv::Point_<float>, std::__1::allocator<cv::Point_<float> > >::__throw_length_error() const in 000024.o
      std::__1::__vector_base<std::__1::vector<cv::Point_<float>, std::__1::allocator<cv::Point_<float> > >, std::__1::allocator<std::__1::vector<cv::Point_<float>, std::__1::allocator<cv::Point_<float> > > > >::__throw_length_error() const in 000024.o
      std::__1::__vector_base<cv::Point3_<float>, std::__1::allocator<cv::Point3_<float> > >::__throw_length_error() const in 000024.o
      ...
  "std::__1::__vector_base_common<true>::__throw_out_of_range() const", referenced from:
      std::__1::__vector_base<cv::Point_<int>, std::__1::allocator<cv::Point_<int> > >::__throw_out_of_range() const in 000024.o
      std::__1::__vector_base<std::__1::vector<cv::Point_<int>, std::__1::allocator<cv::Point_<int> > >, std::__1::allocator<std::__1::vector<cv::Point_<int>, std::__1::allocator<cv::Point_<int> > > > >::__throw_out_of_range() const in 000024.o
      std::__1::__vector_base<cv::Point_<float>, std::__1::allocator<cv::Point_<float> > >::__throw_out_of_range() const in 000024.o
      std::__1::__vector_base<std::__1::vector<cv::Point_<float>, std::__1::allocator<cv::Point_<float> > >, std::__1::allocator<std::__1::vector<cv::Point_<float>, std::__1::allocator<cv::Point_<float> > > > >::__throw_out_of_range() const in 000024.o
      std::__1::__vector_base<cv::Point3_<float>, std::__1::allocator<cv::Point3_<float> > >::__throw_out_of_range() const in 000024.o
      std::__1::__vector_base<std::__1::vector<cv::Point3_<float>, std::__1::allocator<cv::Point3_<float> > >, std::__1::allocator<std::__1::vector<cv::Point3_<float>, std::__1::allocator<cv::Point3_<float> > > > >::__throw_out_of_range() const in 000024.o
  "std::__1::__basic_string_common<true>::__throw_length_error() const", referenced from:
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__throw_length_error() const in 000025.o
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__throw_length_error() const in 000027.o
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__throw_length_error() const in 000028.o
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__throw_length_error() const in 000029.o
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__throw_length_error() const in 000030.o
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__throw_length_error() const in 000035.o
  "std::logic_error::logic_error(char const*)", referenced from:
      std::length_error::length_error(char const*) in 000024.o
      std::length_error::length_error(char const*) in 000025.o
      std::length_error::length_error(char const*) in 000026.o
      std::length_error::length_error(char const*) in 000028.o
      std::length_error::length_error(char const*) in 000029.o
      std::length_error::length_error(char const*) in 000030.o
      std::length_error::length_error(char const*) in 000031.o
      ...
  "std::__1::__shared_weak_count::__release_weak()", referenced from:
      _Layer_Close in 000025.o
      _AKAZE_Close in 000026.o
      _AgastFeatureDetector_Close in 000026.o
      _BRISK_Close in 000026.o
      _GFTTDetector_Close in 000026.o
      _KAZE_Close in 000026.o
      _MSER_Close in 000026.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation) (exit status 2

**Comment by BigCatGit** [comment]
新建了几个项目测试, 好像是robotgo库的问题

**Comment by BigCatGit** [comment]
找到原因了: 只要gocv和govcl同时使用就会报错, 目前只能在项目中放弃其中一个库, 有大神能解决的可以告知一下, 谢谢了!
vcl.Application.SetScaled(true)
ico := gocv.IMRead("/Users/xxx/Downloads/13.png", gocv.IMReadGrayScale)
fmt.Println(ico)
if !ico.Empty() {
    defer ico.Close()
}
