### ISSUE TITLE
怎么在TTabSheet中创建TTabSheet？

### ISSUE THREAD

**Issue by clasy0947** [ying32/govcl#136]
在TTabSheet中创建TTabSheet时遇到错误：
![image](https://user-images.githubusercontent.com/79400678/177006043-2aacf503-bf24-41f6-9c29-1219a2167094.png)

**Comment by ying32** [comment]
TTabSheet是TPageControl的固定子控件，要在这个上面创建就得先在这个TTabSheet上创建TPageControl，再将新创建的TTabSheet放到TPageControl。
