### ISSUE TITLE
请问windows任务栏的缩略图怎么设置

### ISSUE THREAD

**Issue by j787701730** [ying32/govcl#140]
![image](https://user-images.githubusercontent.com/23625690/181879962-4b54d6e7-1b54-4927-abb2-9255f741a50b.png)
我看了例子里mp3Player和taskbar, 没有找到. 望指导, 感谢.

**Comment by ying32** [comment]
原来vcl版本有的，现在的版本没有了，

**Comment by j787701730** [comment]
@ying32 好的, 谢谢
