### ISSUE TITLE
MacOS with M1 lots of errors

### ISSUE THREAD

**Issue by marcelloh** [ying32/govcl#146]
So I've downloaded the "Pre-compiled GUI library binary download"
and extracted the "macOS64-cocoa" version of "liblcl.dylib" to the directory where my go-software is.
When I try to run it, this is what I get:

ld: warning: object file (/var/folders/2j/sl_kv1311vggqj0m8jy3_w7w0000gn/T/go-link-3205247113/000003.o) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/var/folders/2j/sl_kv1311vggqj0m8jy3_w7w0000gn/T/go-link-3205247113/000005.o) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: ld: warning: object file (/var/folders/2j/sl_kv1311vggqj0m8jy3_w7w0000gn/T/go-link-3205247113/000007.o) was built for newer macOS version (12.0) than being linked (11.0)
object file (/var/folders/2j/sl_kv1311vggqj0m8jy3_w7w0000gn/T/go-link-3205247113/000004.o) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: ld: warning: object file (/var/folders/2j/sl_kv1311vggqj0m8jy3_w7w0000gn/T/go-link-3205247113/000010.o) was built for newer macOS version (12.0) than being linked (11.0)ld: warning: ld: warning: object file (/var/folders/2j/sl_kv1311vggqj0m8jy3_w7w0000gn/T/go-link-3205247113/000002.o) was built for newer macOS version (12.0) than being linked (11.0)ld: warning: 
object file (/var/folders/2j/sl_kv1311vggqj0m8jy3_w7w0000gn/T/go-link-3205247113/000012.o) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: object file (/var/folders/2j/sl_kv1311vggqj0m8jy3_w7w0000gn/T/go-link-3205247113/000011.o) was built for newer macOS version (12.0) than being linked (11.0)
object file (/var/folders/2j/sl_kv1311vggqj0m8jy3_w7w0000gn/T/go-link-3205247113/000009.o) was built for newer macOS version (12.0) than being linked (11.0)
ld: warning: 
object file (/var/folders/2j/sl_kv1311vggqj0m8jy3_w7w0000gn/T/go-link-3205247113/000006.o) was built for newer macOS version (12.0) than being linked (11.0)
object file (/var/folders/2j/sl_kv1311vggqj0m8jy3_w7w0000gn/T/go-link-3205247113/000008.o) was built for newer macOS version (12.0) than being linked (11.0)
dlopen err: dlopen(/Users/marcelloh/data/go-private/WiMaLiCommander/liblcl.dylib, 0x0009): tried: '/Users/marcelloh/data/go-private/WiMaLiCommander/liblcl.dylib' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))
panic: dlopen("liblcl.dylib"), failed.

goroutine 1 [running]:
github.com/ying32/govcl/vcl/api.loadUILib()
        /Users/marcelloh/data/go-private/WiMaLiCommander/vendor/github.com/ying32/govcl/vcl/api/dylib_nonmemory.go:32 +0xe4
github.com/ying32/govcl/vcl/api.init()
        /Users/marcelloh/data/go-private/WiMaLiCommander/vendor/github.com/ying32/govcl/vcl/api/dylib.go:24 +0x148
exit status 2

**Comment by ying32** [comment]
This is an x64 version of liblcl.dylib. I can‘t provide the arm version.

**Comment by marcelloh** [comment]
Is there anybody who can, or provide the steps for me to provide it to you?

Op wo 28 sep. 2022 om 09:23 schreef 不在乎y ***@***.***>:

**Comment by ying32** [comment]
Look at the [Compile.README](https://github.com/ying32/liblcl/blob/dev/Compile.README.en-US.md) of the dev branch

**Comment by marcelloh** [comment]
So far I did this:
> Install macports
https://www.macports.org/install.php

> install lazarus
sudo port install lazarus

When I double click on the downloaded "liblcl.lpi" lazarus tries to start,
but gives me:
Compiler "/opt/local/bin/ppca64" does not support target i386-win32

How to fix this?


Op wo 28 sep. 2022 om 14:20 schreef 不在乎y ***@***.***>:

**Comment by ying32** [comment]
This error can be ignored, just follow the third step to select the corresponding compilation configuration, M1 seems to need Lazarus 2.2+ version to support. Also for Lazarus and configuration on M1 I have no condition test, so I can't answer other questions.

**Comment by ying32** [comment]
You missed the fourth step. In addition, if m1 configuration is not found, confirm whether the code of the dev branch is not used.

**Comment by marcelloh** [comment]
I did exactly that 4th step.
I've clicked on Build modes and added an extra line....

[image: image.png]

Op do 29 sep. 2022 om 12:59 schreef 不在乎y ***@***.***>:

**Comment by ying32** [comment]
I can't see the picture you're showing. There is no way to know why.
