### ISSUE TITLE
canvas旋转

### ISSUE THREAD

**Issue by yangzj208** [ying32/govcl#149]
请问canvas文字输出怎么旋转90度呢，像下面这样的
![微信图片_20221103115444](https://user-images.githubusercontent.com/29445634/199644811-8b05853a-8fa2-46e3-9984-bb7c96024e57.png)

**Comment by ying32** [comment]
没这功能，如果是windows下可以用winapi处理，网上搜索下有方法的

**Comment by yangzj208** [comment]
感谢，请问给下搜索的关键词了，搜了下没找到想要的

**Comment by ying32** [comment]
搜索`delphi canvas文字旋转`，delphi与lazarus大部分都相通的。

**Comment by yangzj208** [comment]
找到方法了，设置字体的Orientation就可以
