### ISSUE TITLE
请问listview高度可以自适应行数吗？或者怎么计算出表里所有行的高度？

### ISSUE THREAD

**Issue by yangzj208** [ying32/govcl#152]
如题，谢谢

**Comment by ying32** [comment]
没有那功能，至于行高可以看listview自绘的例子

**Comment by yangzj208** [comment]
参照例子，用win.ListView_GetItemRect可以计算出
现在有个问题就是listview通过setheight怎么设置高度无效呢？总是只能显示7行

**Comment by yangzj208** [comment]
布局的原因，这个布局有点诡异，虽然调差不多了，可是有些地方还是不明就理。
感谢
