### ISSUE TITLE
再请教下ui的问题。

### ISSUE THREAD

**Issue by yidevcom** [ying32/govcl#157]
[
![diff](https://user-images.githubusercontent.com/4003458/203785922-78be3f25-819b-47f6-8229-d9170a2e8cf7.png)
我试着用govcl 学习仿照了个登录界面。基本功能都能实现. 细节处还是有差异,有几个问题不知道是从lazarus里还是代码里解决.请大佬赐教.
1: 现在窗口有1像素的白色边框,能否设置颜色.
2:窗口可以设置圆角吗.
3: 图片实现的按钮能否在鼠标悬浮和点击后改变样式.

感谢.govcl牛x.

**Comment by ying32** [comment]
人家是用directui实现的，你要用原生窗口实现很麻烦的，能做成这样已经可以了，边框设置有无边框是不会有你这样的，imageviewr里面不就有图片按钮的三态么。。。

**Comment by yidevcom** [comment]
感谢回复, imageviewer的关闭,最小化等按钮确实有hover样式,但我没有看看到lazarus源文件,在代码里也没有找到对应的.能否给个代码关键字提示?

**Comment by ying32** [comment]
例子里有个imagebutton的的演示

**Comment by yidevcom** [comment]
谢谢,我通过imagebbutton的例子通过放置图片和代码读取实现了. formEvents这个例子里也有图片按钮三态的效果, 不是用代码实现的,能否分享下lazarus源文件呢.

**Comment by ying32** [comment]
这哪来的源码啊……那个gfm就是资源呗，你不会用而已，要用Lazarus的话直接可以设置图片而已

**Comment by yidevcom** [comment]
是啊,一点都不会, lazarus的教程好少.现在还只会加个固定图片,我以为是有.lpi  我再试试,谢谢, close吧

**Comment by yidevcom** [comment]
我找到在lazarus里怎么操作了. 我写下,方便后来人. 用govcl下的TimageButtom, 将三个样式拼接放到一起图里, ImageCount设置为3,即可.  实例有4个的,暂时还不知道是什么意思.

**Comment by ying32** [comment]
https://github.com/ying32/liblcl/blob/master/src/ImageButton.pas  源码里有说明

**Comment by yidevcom** [comment]
![cls](https://user-images.githubusercontent.com/4003458/203924316-9af49b8b-196f-46e9-89e7-ff69710dbdfa.png)
谢谢大佬.已搞定.
