### ISSUE TITLE
sample ListboxCustomdraw exit status 0xc000041d

### ISSUE THREAD

**Issue by Richie-Jang** [ying32/govcl#160]
Hello, 
I studied govcl with sample, 
listboxcustomdraw and listboxcustomdraw2 sample will not run correclty.

On Windows11, Using Library Version 2.2.0
I could see "exit status 0xc000041d" with terminal.

if I skip this line and run 
   listbox.SetStyle(types.LbOwnerDrawFixed)
, I can see Form and default Item handling on ListBox.

Could You please check this. Thank you in advance.

BR
Richie.

**Comment by ying32** [comment]
Special Note 2: If you use go>=1.15 to compile Windows executable files, you must use the -buildmode=exe compilation option, otherwise there will be errors.

**Comment by Richie-Jang** [comment]
Hello Sir, 
Thank you for the advice, Now I can run these sample.
BR,
Richie.
