### ISSUE TITLE
自定义GoVCL组件安装后看不到选项卡

### ISSUE THREAD

**Issue by f2game** [ying32/govcl#163]
![image](https://user-images.githubusercontent.com/66696425/214195057-23b4b4fb-a20c-4370-bd71-a4f67e73e6d7.png)

这样应该是已安装的状态了，根据[Issue#151](https://github.com/ying32/govcl/issues/151)的说明，已经使用了dev分支的源码。

重启Lazarus IDE和电脑都试过了，还是没有GoVCL选项卡：

![image](https://user-images.githubusercontent.com/66696425/214195153-75bb6fcb-7432-463f-a814-7a43263a8057.png)

系统Win11，Lazarus IDE 2.2.4，已安装res2go IDE插件。

我还需要做什么？

**Comment by ying32** [comment]
估计启动的这个Lazarus.exe不是已经安装的那个，新版的Lazarus不知道是不是改了这方面

**Comment by f2game** [comment]
我只有一个Lazarus.exe

![image](https://user-images.githubusercontent.com/66696425/214290162-a5a64f35-71f6-40e5-9b55-3a5b51ef155a.png)

如果是这样的话，还有可能是什么问题？或者哪个版本的Lazarus可以正常使用？

**Comment by ying32** [comment]
这样的话就是没安装成功了，安装成功他会重编译一次Lazarus.exe的

**Comment by f2game** [comment]
点了Install没有任何反应，但是Uninstall可以点击了。

请给一个解决方案，哪个版本可以正常安装自定义GoVCL组件。

**Comment by ying32** [comment]
我自己用的2.2.2版本的没问题，另外你看下你用的是不是liblcl dev分支的代码。

**Comment by f2game** [comment]
尝试了2.2.2成功了，可以开始设计了。

另外有个问题：在2.2.2版本下，LinkLabel看不到文字，设计器和实际运行都看不到，是否是bug？
