### ISSUE TITLE
请教想动态配置AnchorSide*()？

### ISSUE THREAD

**Issue by smallmenu** [ying32/govcl#164]
比如在 Lazarus中点击事件触发：`PageControl.AnchorSideBottom.Control:=SplitterDebug`

在Go中不知道对应的 `PageControl.SetAnchorSideBottom()` 方法可以怎么写?

谢谢

**Comment by ying32** [comment]
`PageControl.AnchorSideBottom.SetControl(SplitterDebug)`

**Comment by smallmenu** [comment]
漂亮。

`PageControl.AnchorSideBottom().SetControl(SplitterDebug)` 正常工作

我之前一直以为要 SetAnchorSideBottom()，然后就不知道参数 `TAnchorSide` 是个啥。
