### ISSUE TITLE
求助关于系统托盘左键使用菜单问题

### ISSUE THREAD

**Issue by 278333422** [ying32/govcl#166]
pm := vcl.NewPopupMenu(mainForm)

	item = vcl.NewMenuItem(mainForm)
	item.SetCaption("退出(&E)")
	item.SetOnClick(func(vcl.IObject) {
		mainForm.Close()
	})
	pm.Items().Add(item)
	trayicon.SetPopupMenu(pm)
	
	trayicon.SetOnClick(func(vcl.IObject) {
		p := vcl.Mouse.CursorPos()
		pm.Popup(p.X, p.Y)
		fmt.Println("TrayIcon Click.")
	})

我想要托盘左键和右键实现同样的效果, 这样写确实会有效果 
但如果是左键弹出菜单后 再去电脑桌面任何地方点击 菜单并不会消失  
请问是我的实现方式不对吗?
刚学这个GUI库,不知道有没有 **通过左键点击触发右键点击** 的方法
谢谢

**Comment by ying32** [comment]
菜单不消失的问题他本身就这样的，至于原因我没去看过他内部的机制
