### ISSUE TITLE
关于开发调试

### ISSUE THREAD

**Issue by neesonqk** [ying32/govcl#167]
目前Mac下开发调试过程比较繁琐 不知道是不是我的使用姿势不正确,

现在的步骤是：
1. 无法直接 `go run .` 看运行结果
2. 必须 `go build` 先编译后再找到编译文件(假设编译为my_app)双击运行才能显示出来
3. 直接`./my_app` 或者 `go run .` 只会输出 `Library Version: 2.x.x` 这样的消息, 没有界面显示

有没有办法直接`go run .`运行看界面呢？

**Comment by ying32** [comment]
文档里不是有么

**Comment by neesonqk** [comment]
之前看名字以为只是打包用的 感谢

**Comment by neesonqk** [comment]
另外，MacOS 12 以后貌似需要自己编译一份liblcl.dylib, 预编译的报找不到 `lstdc++`这个lib，我是编译一下`liblcl.dylib`再切到dev分支然后就可以了, 大概看了一眼应该是link的一个依赖变了。

**Comment by ying32** [comment]
没有macos 12啊，没得办法细究

**Comment by neesonqk** [comment]
贴一下我编译好的

[liblcl.dylib.zip](https://github.com/ying32/govcl/files/10904540/liblcl.dylib.zip)
