### ISSUE TITLE
Lazarus安装res2go组件报错问题

### ISSUE THREAD

**Issue by panghusec** [ying32/govcl#169]
大佬好,  小弟安装最新的lazarus后 根据教程安装这些插件 一点 install就编译报错 导致无法后续学习。网上资料几乎没有 求指教是什么问题
![image](https://user-images.githubusercontent.com/42397796/228107954-e2c18f2f-7cb2-4842-a098-60b642222dbc.png)

**Comment by ying32** [comment]
用dev分支的+Lazarus2.2.2
