### ISSUE TITLE
应用程序代码中引入 “C” 会导致链接不过

### ISSUE THREAD

**Issue by maoshigui** [ying32/govcl#17]
windows系统下，使用框架后，在业务代码中原来有引入C库的代码，会变成链接不通过了。错误提示如下。需要配置什么吗？
c:\go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
C:\Users\xx\AppData\Local\Temp\go-link-667343987\000000.o: file not recognized: File format not recognized
collect2.exe: error: ld returned 1 exit status

**Comment by ying32** [comment]
这个问题理论上不应该……不过目前没得测试环境去找这个问题……
