### ISSUE TITLE
TListView滚动至底部

### ISSUE THREAD

**Issue by 278333422** [ying32/govcl#173]
请问  listview怎么设置滚动到最底部呢
我用以下代码会报错 `[TCustomForm.SetFocus] Form1:tGoForm Can not focus`
 
	Form1.ListView1.SetItemIndex(Form1.ListView1.Items().Count() - 1)
	Form1.ListView1.SetFocus()
谢谢

**Comment by ying32** [comment]
listview的例子里不是有么
