### ISSUE TITLE
想实现一个检索窗口，如图。输入框输入内容，在输入框下方显示一个窗口用来显示检索结果，点击可以选中相应内容，这个是用到哪个组件

### ISSUE THREAD

**Issue by wanghuaming8** [ying32/govcl#174]
![微信图片_20230625092702](https://github.com/ying32/govcl/assets/127464623/197c130d-4468-4ad9-9abc-17802d80f1e5)

**Comment by ying32** [comment]
类似这种的就是Tcombobox组件了，但显然不符合你这个，需要自己用TEdit然后新建一个无边框的form，里面放个listbox来实现。

**Comment by wanghuaming8** [comment]
感谢回复！
通过您的思路已实现。

用到的组件：
TEdit
|Panel
|--ListBox

事件：
TEdit: SetOnChange()，SetOnClick()，SetOnExit()
ListBox: SetOnClick(）
![微信图片_20230627101206](https://github.com/ying32/govcl/assets/127464623/cc84843a-38f9-4095-862f-f50c3b18e192)
![微信图片_20230627101212](https://github.com/ying32/govcl/assets/127464623/66aaef4f-1d12-40c3-8010-35aafd62a9a9)
