### ISSUE TITLE
运行 imageviewer demo报错

### ISSUE THREAD

**Issue by CindyBoy** [ying32/govcl#177]
系统：MocOS M1
 github.com/ying32/govcl/vcl/api
github.com/ying32/govcl@v2.2.0+incompatible/vcl/api/importFuncsAuto.go:392:53: undefined: TMessage

**Comment by ying32** [comment]
主分支的目前不支持m1，只有dev分支的支持，另外需要自己编译m1下的dylib，我没条件能提供
