### ISSUE TITLE
linux 平台下，启动程序前出现莫名窗口

### ISSUE THREAD

**Issue by sanikoyes** [ying32/govcl#179]
我在linux系统下，编译的程序启动时，会出现一个未知窗口，这个窗口的名字是executable name，且出现几秒钟后会自动关闭，等待它自动关闭或者手动关闭后，才会出现程序自己的窗口，是什么原因？
代码用的就是govcl主页里提供的sample code：
```golang
func main() {
	vcl.RunApp(&mainForm, &aboutForm)
}
```

![image](https://github.com/ying32/govcl/assets/6880378/04bbc91d-18a9-46ec-b353-b1c6fa87e6c6)

liblcl库：https://github.com/ying32/govcl/releases/download/v2.2.3/liblcl-2.2.3.zip
govcl版本：github.com/ying32/govcl v2.2.3+incompatible
系统：Linux DESKTOP-K9HTF91 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
go版本：go version go1.18.1 linux/amd64

**Comment by ying32** [comment]
额，看你这是wsl啊……。正常的linux系统是没这种问题的，我试过几款linux桌面系统都没这样的

**Comment by sanikoyes** [comment]
好吧，看起来不是liblcl的问题，我记得lazarus编译后的程序也有这毛病
