### ISSUE TITLE
去掉黑框问题

### ISSUE THREAD

**Issue by Jumpro** [ying32/govcl#180]
去掉黑框后，运行后会有黑框闪烁，闪一下后自动关闭。。

**Comment by ying32** [comment]
你这应该是崩溃了，具体原因你可以调试看看

**Comment by Jumpro** [comment]
不是的，应用运行正常，但操作一下就会闪一下cmd黑框，cmd黑框自动关闭，再操作又会闪黑框。如果不去掉黑框，应用就没有这个现象。

**Comment by ying32** [comment]
那你这个奇怪了，没遇到过，我觉得你还是用调试模式抓下看有没有异常信息吧，光脑补也判断不了你的问题

**Comment by Jumpro** [comment]
库没有问题，我自己的问题，谢谢。
