### ISSUE TITLE
TPageControl has no TabVisible property available

### ISSUE THREAD

**Issue by nxshock** [ying32/govcl#181]
I want to use `TPageControl` without visible tabs. In GoVCLDesigner `TPageControl.TabVisible` property is available, but I want to create app without GoVCLDesigner.

Can you make `TPageControl.TabVisible` available from source code?

**Comment by ying32** [comment]
https://github.com/ying32/govcl/blob/master/samples/pagecontrolwizard/MainFormImpl.go

only windows.

**Comment by nxshock** [comment]
Confirmed, `TTabSheet.SetTabVisible(false)` for all of sheets does this job.
