### ISSUE TITLE
initFile 中readDate、readTime、readDateTime三个返回的是0，导致解析成1970-01-01....

### ISSUE THREAD

**Issue by ycyaw-fun** [ying32/govcl#183]
initFile 中readDate、readTime、readDateTime三个返回的是0，导致解析成1970-01-01....

环境win10、amd64

**Comment by ycyaw-fun** [comment]
貌似syscallN返回的r1是正确的

**Comment by ying32** [comment]
看了下，是之前修改了一些地方造成的，还没想好怎么修复
