### ISSUE TITLE
res2go doesn't work.

### ISSUE THREAD

**Issue by skyqvn** [ying32/govcl#184]
Why???
![image](https://github.com/ying32/govcl/assets/103918104/92ead65b-0367-4e8c-a4c5-b8af56fd2097)

![image](https://github.com/ying32/govcl/assets/103918104/fd7e76a3-c1a9-43a4-9258-8e4663a556b9)

go version go1.21.0 windows/amd64

I can't find the argument '-i' in 'go help build'.

**Comment by ying32** [comment]
里面有个设置，勾选使用go embed的那个就行了

**Comment by skyqvn** [comment]
> 里面有个设置，勾选使用go embed的那个就行了

跟go:embed没关系，是因为go build根本就没有“-i”这个参数，怎么能关闭“-i”参数？
> 我在Goland也遇到过类似问题，但它的“-i”参数在tags里，删掉就行了，建议把-i移到Tags，就像这样：
![image](https://github.com/ying32/govcl/assets/103918104/401af031-03be-41ef-be94-1863ce5024ce)

**Comment by skyqvn** [comment]
刚刚看了下源码，是的，勾选go:embed之后就不会使用-i了.However，事实就是仍然有一定概率有“-i”（我一直都是勾选go:embed的，有时候没有-i，但大多数情况有-i）

**Comment by ying32** [comment]
没遇到过，不过如果你不需要太复杂的设计可以用主页提供的简易UI设计器来做

**Comment by skyqvn** [comment]
改了下源代码，把ugolang.pas第142行注释了，重装就没问题了.
顺便问一句，这三个组件是不支持吗？
![image](https://github.com/ying32/govcl/assets/103918104/ea49f2c3-c72c-42ed-9a9a-f032e1501c04)

**Comment by skyqvn** [comment]
总而言之，感谢回复！！！ 
![122FE6E3](https://github.com/ying32/govcl/assets/103918104/356834c3-5f77-470e-92fb-98e1fe16db88)

**Comment by skyqvn** [comment]
我好想找到规律了（虽然我看不懂Pascal）：新建一个项目，勾选go:embed，编译，报错；重启电脑（不是Lazarus），就可以了.所以我怀疑是不是go:embed写入了配置文件，但没有更新到内存，导致仍然有“-i”参数.

**Comment by ying32** [comment]
res2go-ideplugin项目已经提交修复，可以拉下代码重新编译安装插件即可。
