### ISSUE TITLE
这几个组件是不支持吗？

### ISSUE THREAD

**Issue by skyqvn** [ying32/govcl#186]
![image](https://github.com/ying32/govcl/assets/103918104/877b0390-5c14-4afd-aba1-ac2f0779785b)
这几个组件是不支持吗，还是转换时名字错了？

**Comment by ying32** [comment]
[完整的支持列表](https://gitee.com/ying32/govcl/wikis/pages?sort_id=174120&doc_id=102420)，

**Comment by skyqvn** [comment]
什么时候可以支持TPairSplitterSide?好想要，嘻嘻
