### ISSUE TITLE
生成名称属性已更改的控件时出错

### ISSUE THREAD

**Issue by WillyAguilera1977** [ying32/govcl#188]
当您更改控件的名称属性时，该控件不会出现在结构的字段列表中。
我展示下面的代码：

type TForm1 struct {
    *vcl.TForm
    //已在 name 属性中命名的控件不会出现

    // ::private::
    TForm1Fields
}

如果我使用 Lazarus IDE，也会发生同样的情况

这里我传递了一个包含 GoVCLDesigner 生成的项目的 zip 文件。

等待您的回复，我真诚地向您问好。

抱歉我不会说中文，我正在使用谷歌翻译

[GoVCLDesigner项目.zip](https://github.com/ying32/govcl/files/14028684/GoVCLDesigner.zip)

**Comment by ying32** [comment]
The first letter of the control name needs to be uppercase, and those starting with lowercase will be filtered. Because only the first letters in go are defined as public members or methods, Rtti requires public members/methods. (控件名首字母需要大写，小写开头的会被过滤。因为go中首字母大写的才会被定义为公开的成员或者方法，Rtti需要公开的成员/方法。 )

**Comment by skyqvn** [comment]
The name 'lblName','edName' and 'btnRun' is not valid.
You can name it 'LblName','EdName' and 'BtnRun'
