### ISSUE TITLE
MacOS 下面XButton的Caption字体模糊

### ISSUE THREAD

**Issue by kindevil** [ying32/govcl#197]
使用了XButton这个组件，在 Windows和Liunx字体显示都正常，就是在MacOS 下面字体看着有点模糊。
<img width="94" alt="截屏2024-03-30 12 56 43" src="https://github.com/ying32/govcl/assets/846488/46a97dc3-b9e0-459c-9532-0e0f4124d20c">

<img width="94" alt="截屏2024-03-30 13 01 25" src="https://github.com/ying32/govcl/assets/846488/f6699021-6958-46c2-8333-fa378d5315a1">

上面那个是MACOS下面的，下面的是Windows 系统下面的。
有没有什么办法可以解决这个问题啊？

**Comment by ying32** [comment]
估计是dpi问题。如果是mac14x的系统我估计可能知道原因，如果可以的换安装最新的Lazarus编译liblcl看看

**Comment by kindevil** [comment]
是14的版本，我试试看，多谢🙏

**Comment by kindevil** [comment]
我换了最新的Lazarus编译liblcl之后这个问题还是没有解决🤦

**Comment by ying32** [comment]
其它控件的字体有这问题么？

**Comment by kindevil** [comment]
目前就发现了这一个，因为我用的控件也不多，就图里面这么几种。别的我找了几个测了一下没有发现这个问题。

<img width="800" alt="image" src="https://github.com/ying32/govcl/assets/846488/e744cb32-46ca-4cd4-9fc3-c8153cc03f9e">

**Comment by ying32** [comment]
在虚拟机里折腾了半天，终于是改好了这个问题。重新拉取[liblcl](https://github.com/ying32/liblcl)，然后编译，替换掉原来的liblcl.dylib就可以了。我在虚拟机里测试了高dpi下没问题了。

**Comment by kindevil** [comment]
测试了一下确实没问题了，多谢了 🙏
