### ISSUE TITLE
为什么不使用 syscall.LazyDLL 加载 liblcl 模块? 应该允许用户在调用 vcl.Application.Initialize 初始化之前动态释放 liblcl模块.

### ISSUE THREAD

**Issue by funte** [ying32/govcl#198]

**Comment by ying32** [comment]
1、以前用的这个，但后面有其它需求，这个达不到，就换了。
2、因为liblcl不需要用户来管理，而且你想要初始化之前动态释放，那程序就直接挂了啊，所以我不是很明白你想表达什么，如果你是要自定义加载指定路径的例子里有有一个这样。
