### ISSUE TITLE
Method 2里的按钮样式不是系统样式？

### ISSUE THREAD

**Issue by joylin1984** [ying32/govcl#20]
系统：win10 1607 
golang： 1.11.4
govcl：最新。
按照readme里的实例：
Method 1里的按钮样式没问题，和系统一致。而Method 2里的按钮样式不是系统样式？

![2018-12-19_231516](https://user-images.githubusercontent.com/13713368/50228896-04d4ea00-03e4-11e9-8a64-648d0ee5a1d2.png)

**Comment by ying32** [comment]
参考Wiki中关于manifest
