### ISSUE TITLE
TImage 的 BeginDrag(bool)方法没有

### ISSUE THREAD

**Issue by lnxyz** [ying32/govcl#206]
TImage 的 BeginDrag(bool) 方法没有, 有没有其它替代的？

**Comment by ying32** [comment]
确实没有封装相关方法，不知道你需要实现一个什么样的功能？
如果只是想用鼠标移动TImage，可以参考`imageviewer`这个例子。

**Comment by lnxyz** [comment]
> 确实没有封装相关方法，不知道你需要实现一个什么样的功能？ 如果只是想用鼠标移动TImage，可以参考`imageviewer`这个例子。

只是想 将 论坛 这个 图片间拖拉 交换位置功能 复现 : https://forum.lazarus.freepascal.org/index.php?topic=32500.0   但我发现 完全不用这个 beginDrag 也行。对，你示例这个也很好。所以这个问题可以关掉了。
