### ISSUE TITLE
我要实现一个类似设计器的功能 应该用哪个组件

### ISSUE THREAD

**Issue by lyglj** [ying32/govcl#208]
这个设计器 要可以放入N个 Text 可以设置文字内容  拖动位置 调整字体大小 二维码 ，图片这些，最终设计的界面是为了处理后发送给打印机的，类似打印模板。请问能实现吗？和你的govclui设计器类似 只是我只放少量的控件 文字 图片 二维码

**Comment by ying32** [comment]
没有提供这样的组件哦。如果不熟悉lazarus的话，估计做起来有点麻烦。
