### ISSUE TITLE
请教关于嵌入式浏览器的问题？

### ISSUE THREAD

**Issue by bsdstar** [ying32/govcl#209]
我是个GUI新手小白，刚了解到这个库很喜欢，我平时使用chromedp现实一些自动化项目，这个GUI库，可以嵌入chromedp浏览器操作吗？谢谢。

**Comment by ying32** [comment]
可以嵌入，但得自己封装并编译到liblcl中，再实现go中的接口……嗯，不会的话确实会很麻烦。

**Comment by bsdstar** [comment]
谢谢你的回复，你这么一说，确实感觉有点麻烦。现在关于爬虫和网页自动化方面的需要还是比较多。看以后可有可能加个这个功能组件。

**Comment by ying32** [comment]
好像有人做了个加入cef组件的liblcl，不过我这个版本不会加入的，主要是因为那东西太大了，不适合标准库。

**Comment by ying32** [comment]
好像有人做了个加入cef组件的liblcl，不过我这个版本不会加入的，主要是因为那东西太大了，不适合标准库。
