### ISSUE TITLE
splitter 感觉有些属性不好设置，比如想实现可以垂直split，改变上下两个控件大小，好像没法设置？

### ISSUE THREAD

**Issue by maoshigui** [ying32/govcl#21]
另外，目前好像没法设置AnchorSide，边界不好定锚点，好像也不好实现动态改变控件大小的效果。这些都有办法绕过去吗？多谢

**Comment by maoshigui** [comment]
搞定了，按照顺序定义和初始化控件，并设置top对其，就行了

**Comment by ying32** [comment]
是的，调整控件的创建顺序及设置相应的Align属性即可。
