### ISSUE TITLE
vcl.TStrings报错

### ISSUE THREAD

**Issue by skyqvn** [ying32/govcl#210]
```go
s := vcl.NewStrings()
s.AddStrings2([]string{"a", "b", "c"})
fmt.Println(s.S(0))
```
这些方法都会报错
![image](https://github.com/user-attachments/assets/8d459d43-87a7-406c-8e11-073442ac0fd1)

**Comment by skyqvn** [comment]
是我使用有问题吗？TListBox的items一定要用Tstrings设置吗？

**Comment by ying32** [comment]
1、如果要创建一个`TStrings`需要用`NewStringList`来创建，因为`TStrings`是一个抽象的类。
2、`TListBox`的`Items`属性是实例类，可以直接操作的。比如：
```go
  ListBox1.Items().Add("ffdfd")
```

**Comment by skyqvn** [comment]
谢谢！
