### ISSUE TITLE
目前支持 Lazarus 哪些版本？

### ISSUE THREAD

**Issue by smallmenu** [ying32/govcl#213]
你好，最新的 3.6 支持吗？

**Comment by ying32** [comment]
Lazarus一般都是向下兼容的，

**Comment by smallmenu** [comment]
Mac 上 Lazarus 3.6  安装 res2go 的时候提示：
无法找到 datetimepicker.pas

**Comment by ying32** [comment]
我看了下res2go并没有引用这个单元，这个应该是lazarus调整了什么东西导致重新编译ide时找不到依赖。目前暂没环境可去测试了

**Comment by smallmenu** [comment]
遇到一个新问题，Mac下面 go build 提示这个：
github.com/ying32/dylib: build constraints exclude all Go files in /usr/local/go/pkg/mod/github.com/ying32/dylib@v0.0.0-20220227124818-fdf9ea9fbc96

**Comment by smallmenu** [comment]
> 遇到一个新问题，Mac下面 go build 提示这个： github.com/ying32/dylib: build constraints exclude all Go files in /usr/local/go/pkg/mod/github.com/ying32/dylib@v0.0.0-20220227124818-fdf9ea9fbc96

啊。估计是忘记开启CGO_ENABLE=1

**Comment by ying32** [comment]
看着确实像是这样
