### ISSUE TITLE
Mac 下的 Goland 没办法调试呢，以前是可以的

### ISSUE THREAD

**Issue by smallmenu** [ying32/govcl#215]
go1.20.14
GoLand 2023.3.8
dlv 1.22.0

使用的：
github.com/ying32/govcl v2.2.3

运行，build都没问题，但是没办法Debug断点。
Debug的时候只能进入到github.com/ying32/govcl/pkgs/macapp 里面。然后启动窗体后就没办法断点了。

我感觉是 dlv 的目标不对。

点调试，默认dlv 对象是 XXX/JetBrains/GoLand2023.3/tmp/GoLand/___4client，

实际应该是XXX/JetBrains/GoLand2023.3/tmp/GoLand/___4client.app/Contents/MacOS/__4client

**Comment by ying32** [comment]
我估计不导入macapp这个包估计可行，但会有点输入框的问题

**Comment by smallmenu** [comment]
试了一下，不导入这个包，运行后窗体或控件都很多莫名其妙的问题。

有什么其他解决办法么？

**Comment by ying32** [comment]
暂时没啥好办法，如果不是必须，考虑用fmt.Println

**Comment by smallmenu** [comment]
Windows是可以的。有没有什么姿势魔改一下？

**Comment by ying32** [comment]
暂时没有啊

**Comment by smallmenu** [comment]
MacOS 下现在go build打包后，icon图标是默认的。
是不是在 macapp 里把 macOSAppIcon 自动复制进去了。

没办法在 build 的时候修改吗，总不能每次去更新 Info.plist 吧？

**Comment by ying32** [comment]
这个包其实是个测试时用的，在文档[APP打包](https://gitee.com/ying32/govcl/wikis/pages?sort_id=410056&doc_id=102420)里有说明的，正式打包可以用第三工具的（我记得有个go写的打包工具），或者自己写个shell也行哈。

**Comment by smallmenu** [comment]
好的。我想再请教一个问题。

如何实现，避免程序重复运行。如果已经有运行的实例就将它自动推到前端（当前程序使用了系统托盘功能）
参考大部分windows上的应用程序实现，比如：微信客户端。

**Comment by ying32** [comment]
如果是windows下，例子里有个类似的WindowsTest，至于显示已打开的可以通过记录已运行的窗口句柄，可以是文件或者其他方式，然后通过自定义一个wm消息postmessage到记录的窗口。如果是其他平台我就不知道了…
