### ISSUE TITLE
This project could go viral 

### ISSUE THREAD

**Issue by caryyu** [ying32/govcl#217]
I don't know if the Delphi official is aware of the Golang's popularity, I guess if Delphi RAD integrates its VCL approach, that could probably attract so many Golang programmers to join in since Golang's syntax is very simple and easy to understand compared to what Pascal does.

**Comment by ying32** [comment]
你想多了，这是不可能存在的事！

**Comment by caryyu** [comment]
@ying32   Seems like here's a compatible issue with the higher Golang version.

- go version go1.23.4 windows/amd64

```
go build -i -buildmode=exe -ldflags="-H windowsgui" -o "D:\govclapp\govclapp.exe": Exit code 2, Errors: 1
flag provided but not defined: -i
usage: go build [-o output] [build flags] [packages]
Run 'go help build' for details.
Panic: tool stopped with exit code 2. Use context menu to get more information.
```

**Comment by ying32** [comment]
error: `flag provided but not defined: -i` 
```go
go build -buildmode=exe -ldflags="-H windowsgui" -o "D:\govclapp\govclapp.exe"
```

**Comment by caryyu** [comment]
@ying32 do you know any possible reasons the exe file can't start successfully, even if it's just a very simple hello world application based on the Lazarus lfm Forms. the symptom is just like: when you double click it, it exits without any information.

BTW: this exe file is compiled by golang 1.10.

**Comment by ying32** [comment]
从描述上看，很大可能是缺少对应版本或者对应arch的liblcl.dll。
