### ISSUE TITLE
想实现trerlist的效果（多列的tree），搜到一个第三方控件，该任何支持呢？

### ISSUE THREAD

**Issue by maoshigui** [ying32/govcl#22]
控件在https://github.com/benibela/treelistview。修改res2go支持该控件好像还好，但是vcl里面要增加相应的控件代码就不太容易了。看注释以前都是GenlibVcl自动生成的，能否提供一下支持？工具可以从哪里下载到吗？或者是否有其他办法，实现多列的tree的效果呢？非常感谢

**Comment by ying32** [comment]
这个可麻烦了，我看你这个控件也挺复杂的，govcl一开始到现在都没有打算过支持第三方控件，所以也就没有这方面文档，至于Genlibvcl这个工具因为写得很随意也就没有放出来的打算。

> 要自己添加第三控件，需要几个步骤。

* 1、uses相关第三方控件的单元到libvcl或者liblcl源码中。
* 2、生成相应的inc文件，此步是为了导出需要的属性和方法，并加入到libvcl或者liblcl。比如TButton的inc文件：UILibSources/libvcl/Button.inc
* 3、导入dll中的API，例如：vcl/api/importAuto.go中的格式。
* 4、以go方法重新封装一遍api，比如：vcl/api/importFuncsAuto.go中的（如果嫌麻烦也可以不要这步）
* 5、生成以结构的伪类形式，比如：/vcl/button.go
* 6、编译libvcl或者liblcl。

> 如果涉及到不支持的事件，那还需要自己导出事件代码那还需要更多的支持  

* 1、定义和传递事件，参考 UILibSources/libvcl/uEventCallback.pas或者UILibSources/liblcl/uEventCallback.pas
* 2、重复并合并到上面2，3，5，6点中的。
* 3、在参考vcl/events.go定义事件类型。
* 4、然后在vcl/callbackevent.go处理事件。

> 如果涉及到新类型的定义，参考vcl/types包进行定义

总结点：过于复杂的控件可以进行简单封装，把相关的api简化后导出，这样工作量就小很多。
