### ISSUE TITLE
请问有没有Clone方法

### ISSUE THREAD

**Issue by JulianZhao** [ying32/govcl#221]
记得Delphi里控件实例有Clone方法，
比如Panel1里有很多子控件，
只需要Clone这个Panel1就可以复制出带子控件的Panel实例
我找了一下好像只有Assign
但我用Assign的时候报错：
Cannot assign a TPanel to  a TPanel.

麻烦帮忙看看，多谢！

**Comment by ying32** [comment]
你记错了，没有这种功能，你所说的Assign这东西一般只有实现了的才有，像TBitmap等等之类的不可视对象
