### ISSUE TITLE
why VCL and not focusing only on LCL ?

### ISSUE THREAD

**Issue by ffred** [ying32/govcl#26]
Hello,
no problem here, I'm just curious to know why you don't focus only on supporting LCL, which is  free and cross-platform and still keep supporting VCL which is not cross-platform and mostly not really free (except for open source development if I understand well). 
so you have to be compatible with both of them and restrict the functions to what is common between them...
is VCL really better or does it have some specials possibilities that could justify to keep supporting it ?

please just consider my question as the expression of my curiosity, I do not want to blame you for anything. you have made a really great work with govcl, thanks for that !!

**Comment by ying32** [comment]
Hi!

Because VCL is more stable than LCL, there are fewer bugs.

**Comment by ffred60** [comment]
ok, thanks..

**Comment by ffred** [comment]
Hi,
sorry, very little time available actually to keep learning Golang.

**govcl** seems really nice and I think it could be a good candidate for general Golang UI.
there are a lot of UI library for Go, but most of them are now unmaintained or with too limited capacity, not complete or not cross-platform or too complex/heavy for no good result, etc...
the **lcl** side of **govcl** could be a good option.
that's just my point of vue, but even if LCL got more bugs, they could be reported and/or solved with time, and I'm sure that govcl will have more users because of it's cross-platform capacity than just because a vcl compatibility.
don't really see the point taking time to be compatible with both VCL & LCL and just keep the common parts.
what would be good to attract more people to use govcl is more English documentation/samples.
I understand that you're not an English "expert" - me neither - (I'm French) but it's the best compromise to touch a larger public and got more contribution.
I saw that other's here proposed help for translation. could do my part also eventually..

again, thanks for your work..

**Comment by ying32** [comment]
Hi!
对于LCL库我也很无奈。这个现在还没有人贡献英文文档，我也没这个能力提供。现在也只提供了部分中文文档。(I am also very helpless about the LCL library. No one has contributed English documents yet, and I don't have the ability to provide them. Only some Chinese documents are now available.)

**Comment by ffred** [comment]
well, Google translate seems to be rather good translating Chinese to English.
tried to translate few pages of your Gitee.com wiki and it's really clear and good enough to be used directly.
only "problem" for me is that sometimes Gitee.com is really slow or I can't see the page content, but not always...

**Comment by ying32** [comment]
没有将GoVCL文档放在github的原因主要是因为github的WIKI功能没有gitee的好用。在中国访问github速度也不快，跟你法国访问gitee一样慢。（The reason for not putting GoVCL documents in GitHub is that github WIKI functionality is not as useful as gitee. Visiting github in China is not fast, as slow as visiting France for gitee.）
