### ISSUE TITLE
增加例程需求

### ISSUE THREAD

**Issue by ying32** [ying32/govcl#27]
可以在此issue下提出你想增加的例程需求，我会根据所提出的例程视情况采纳。
1、不要太过于复杂的需求。
2、不要超出govcl范围。
3、不要提一些不可能实现的需求。

**Comment by ismlsmile** [comment]
1、带CheckBox的TTreeView（lcl不支持的话仅vcl）
2、TListView
（1）Item和SubItem自绘控件：如图片、CheckBox（lcl不支持的话仅vcl）
（2）单元格上色：指定行、指定Item、指定SubItem
3、TStringGrid
（1）排序
（2）自绘控件（如图片、CheckBox）
（3）单元格上色

**Comment by ying32** [comment]
@ismlsmile 
* 1、[带CheckBox的TTreeView，只支持Windows](https://github.com/ying32/govcl/tree/dev/samples/treeview_checkbox)     
* 2、TListView  
  *  (1）、还未做，不过可以参考[listviewcustomdraw](https://github.com/ying32/govcl/tree/dev/samples/listviewcustomdraw)  
  *  (2）、可参考 [listviewcustomdraw](https://github.com/ying32/govcl/tree/dev/samples/listviewcustomdraw)的自绘   
* 3、TStringGrid  
 * (1) 排序未做
 * (2) 自绘控件参考[drawgrid](https://github.com/ying32/govcl/tree/dev/samples/grids/drawgrid)
 * (3) 不咋明白咋样的上色。

**Comment by ismlsmile** [comment]
“单元格上色”指的就是给单元格加个背景色。TListView中我发现个比较怪的问题，在SetOnAdvancedCustomDrawItem事件中，只调用：
sender.Canvas().Brush().SetColor(colors.ClRed)
对第一个Item上色后，后面的SubItem都上成同样颜色了。如果只想对第一列的单元格上色，不知道有什么好的办法？当前我测试时发现可以在SetOnAdvancedCustomDrawSubItem事件中把SubItem的颜色再上回去，但感觉方法比较土。

**Comment by ying32** [comment]
@ismlsmile  TListView的项目就是根据项目的列索引设置Brush的不同颜色

**Comment by ismlsmile** [comment]
比如需求是这样的，只要设置第一列的颜色为红色，但下面的例子中，ListViewAdvancedCustomDrawItem设置后，整行都会变为红色

package main

import (
	"fmt"
	"github.com/ying32/govcl/vcl"
	"github.com/ying32/govcl/vcl/types"
	"github.com/ying32/govcl/vcl/types/colors"
	"math/rand"
)

func main() {
	vcl.Application.Initialize()

	mainForm := vcl.Application.CreateForm()
	mainForm.SetPosition(types.PoScreenCenter)
	mainForm.SetWidth(500)
	mainForm.SetHeight(400)

	lv1 := vcl.NewListView(mainForm)
	lv1.SetParent(mainForm)
	lv1.SetAlign(types.AlTop)
	lv1.SetRowSelect(true)
	lv1.SetReadOnly(true)
	lv1.SetViewStyle(types.VsReport)
	lv1.SetGridLines(true)

	col := lv1.Columns().Add()
	col.SetCaption("序号")
	col.SetWidth(100)

	col = lv1.Columns().Add()
	col.SetCaption("项目1")
	col.SetWidth(200)

	lv1.Items().BeginUpdate()
	for i := 1; i <= 20; i++ {
		item := lv1.Items().Add()
		item.SetCaption(fmt.Sprintf("%d", i+rand.Int()))
		item.SubItems().Add(fmt.Sprintf("值：%d", i+rand.Int()))
	}
	lv1.Items().EndUpdate()

	lv1.SetOnAdvancedCustomDrawItem(ListViewAdvancedCustomDrawItem)

	vcl.Application.Run()
}

func ListViewAdvancedCustomDrawItem(sender *vcl.TListView, item *vcl.TListItem, state types.TCustomDrawState, Stage types.TCustomDrawStage, defaultDraw *bool) {
	sender.Canvas().Brush().SetColor(colors.ClRed)
}

**Comment by ying32** [comment]
@ismlsmile  大概这样子吧

```go
package main

import (
	"fmt"
	"math/rand"

	"github.com/ying32/govcl/vcl"
	"github.com/ying32/govcl/vcl/types"
	"github.com/ying32/govcl/vcl/types/colors"
)

func main() {
	vcl.Application.Initialize()

	mainForm := vcl.Application.CreateForm()
	mainForm.SetPosition(types.PoScreenCenter)
	mainForm.SetWidth(500)
	mainForm.SetHeight(400)

	lv1 := vcl.NewListView(mainForm)
	lv1.SetParent(mainForm)
	lv1.SetAlign(types.AlTop)
	lv1.SetRowSelect(true)
	lv1.SetReadOnly(true)
	lv1.SetViewStyle(types.VsReport)
	lv1.SetGridLines(true)

	col := lv1.Columns().Add()
	col.SetCaption("序号")
	col.SetWidth(100)

	col = lv1.Columns().Add()
	col.SetCaption("项目1")
	col.SetWidth(200)

	lv1.Items().BeginUpdate()
	for i := 1; i <= 20; i++ {
		item := lv1.Items().Add()
		item.SetCaption(fmt.Sprintf("%d", i+rand.Int()))
		item.SubItems().Add(fmt.Sprintf("值：%d", i+rand.Int()))
	}
	lv1.Items().EndUpdate()

	lv1.SetOnAdvancedCustomDrawItem(ListViewAdvancedCustomDrawItem)
	lv1.SetOnAdvancedCustomDrawSubItem(lvTraiAdvancedCustomDrawSubItem)

	vcl.Application.Run()
}

func lvTraiAdvancedCustomDrawSubItem(sender *vcl.TListView, item *vcl.TListItem, subItem int32,
	state types.TCustomDrawState, stage types.TCustomDrawStage, defaultDraw *bool) {
	canvas := sender.Canvas()

	switch subItem {
	case 0:
		canvas.Brush().SetColor(0x02E0F0F7)
	default:
		canvas.Brush().SetColor(0x02F0EEF7)
	}
}

func ListViewAdvancedCustomDrawItem(sender *vcl.TListView, item *vcl.TListItem, state types.TCustomDrawState, Stage types.TCustomDrawStage, defaultDraw *bool) {

	sender.Canvas().Brush().SetColor(colors.ClRed)
}


```
![微信截图_20190428112802](https://user-images.githubusercontent.com/7037165/56858190-b98da200-69a8-11e9-8020-c2ced67b4b49.png)

**Comment by ismlsmile** [comment]
前面我就是这么弄的：），就是感觉有点啰嗦，要写两个方法，如果没有其它更好的办法，就先这么弄吧，多谢了。

**Comment by afocus** [comment]
如何将新建的Canvas对象添加到mainform中  NewCanvas()没有参数

**Comment by afocus** [comment]
1. 如何新建一个存粹的canvas到form中
2. 简单的利用canvas画矩形和其他简单图形的方法

`package main

import (
	"github.com/ying32/govcl/vcl"
	"github.com/ying32/govcl/vcl/types"
)

func main() {
	vcl.Application.Initialize()

	mainForm := vcl.Application.CreateForm()

	mainForm.SetCaption("Hello")
	mainForm.EnabledMaximize(false)
	mainForm.ScreenCenter()

	
	// 暂时使用空白图像当作画布
	img := vcl.NewImage(mainForm)
	img.SetAlign(types.AlTop)
	img.SetBounds(30, 30, 300, 300)
	ctx := img.Canvas()

	// 画一个黑色的矩形
	c := vcl.NewBrush()
	c.SetColor(0x000000)
	ctx.SetBrush(c)
	ctx.Rectangle(10, 10, 100, 100)

	vcl.Application.Run()
}
`
这样没有效果
