### ISSUE TITLE
支持vcl下的TCardPanel

### ISSUE THREAD

**Issue by ismlsmile** [ying32/govcl#28]
类似于Qt下的QStackedWidget，Flex中的ViewStack。TPageControl可以部分模拟，但效果不太好。虽然只支持vcl，但某些特殊情况下还是比较有用，希望能够支持，多谢！

**Comment by ying32** [comment]
这得把Delphi升到10.3啊，要不你看看我写的就在dev分支中pagecontrolwizard，我用来模拟这个控件的

**Comment by ismlsmile** [comment]
看了下，背景色有问题，其它没问题，那我就先这么用吧。

**Comment by ying32** [comment]
背景色问题可以在每个sheet上方放一个TPanel我现在就这么解决的

**Comment by ismlsmile** [comment]
这是个好方法！
