### ISSUE TITLE
在 go() 中执行 form.ShowModal 导致form或者parent卡死

### ISSUE THREAD

**Issue by aj3423** [ying32/govcl#29]
环境是win10 64位，测试代码如下：

	package main

	import (
		"github.com/ying32/govcl/vcl"
	)

	var fm_main *vcl.TForm
	var dlg *vcl.TForm

	func main() {
		vcl.Application.Initialize()
		fm_main = vcl.Application.CreateForm()
		fm_main.EnabledMaximize(false)
		fm_main.ScreenCenter()

		btn_open_dlg := vcl.NewButton(fm_main)
		btn_open_dlg.SetParent(fm_main)
		btn_open_dlg.SetCaption("open dlg")
		btn_open_dlg.SetOnClick(func(sender vcl.IObject) {
			go func() { //  放到独立线程里，关掉dlg就会卡死， 去掉 go func() 直接执行就ok
				dlg.Show() // 或者改成 dlg.ShowModal()
			}()
		})

		dlg = vcl.NewForm(fm_main)
		btn_dlg := vcl.NewButton(dlg)
		btn_dlg.SetParent(dlg)
		btn_dlg.SetCaption("Close Dialog")
		btn_dlg.SetOnClick(func(sender vcl.IObject) {
			dlg.Close()
		})
		vcl.Application.Run()
	}

`dlg.Show()` 会让dlg卡死， `dlg.ShowModal()`关掉dlg后会让主窗体卡死。。

**Comment by aj3423** [comment]
Show() 外面加一层 vcl.ThreadSync 就好了

    btn_open_dlg.SetOnClick(func(sender vcl.IObject) {
        go func() {
            vcl.ThreadSync(func() {
                dlg.Show()
            })
        }()
    })

**Comment by ying32** [comment]
你这样写就跟下面的基本没区别啊。。。。 没有特别情况不要这么写的
```
btn_open_dlg.SetOnClick(func(sender vcl.IObject) {
   dlg.Show()
})
```

**Comment by aj3423** [comment]
btn_open_dlg.SetOnClick(func(sender vcl.IObject) {
        go func() {
            // 这里跑一个状态机，某个状态时候会阻塞方式调用  dlg.Show() 让用户输入数据，所以还是得放到 go func() 里。目前测试下来没啥问题：）
        }()
    })
