### ISSUE TITLE
请问 macOS 怎么把图片打包到资源以及要怎么从资源中加载图片呢？ 

### ISSUE THREAD

**Issue by xpsuper** [ying32/govcl#31]
请问 macOS 怎么把图片打包到资源以及要怎么从资源中加载图片呢？ 谢谢

**Comment by ying32** [comment]
因为macOS不支持windows资源形式的，所以需要把相关的图片等资源以bytes形式放到源码中，然后加载，这个做法可以参考 samples/trayicon 这个示例。

**Comment by xpsuper** [comment]
非常感谢，大神的这个库太棒了
不过，是否有另一个解决方案，就是将 macOS app 加载资源的方法 golang 化，其实就是通过 NSBundle 去加载 app/Contents/Resources  中的资源，找到了这个库 https://github.com/mkrautz/objc，不过好多年没维护了，然后其实 DELPHI 里面应该也有相应的方案 NSStrToStr(TNSBundle.Wrap(TNSBundle.OCClass.mainBundle).bundlePath)
https://stackoverflow.com/questions/48269204/where-do-resource-files-go-when-developing-mac-apps
不知道能否直接包装到 go 里面来

**Comment by ying32** [comment]
app/Contents/Resources 这也就一个路径，也就普通的放进去的，没有嵌入到app里面，用不用那些库都无所谓，
