### ISSUE TITLE
我使用的是deplhi10.1,无法编译vcl.dll

### ISSUE THREAD

**Issue by xtrn143** [ying32/govcl#32]
![image](https://user-images.githubusercontent.com/36922732/63481851-6f857a80-c4c9-11e9-9c5e-e81fa8ae6ee4.png)

**Comment by ying32** [comment]
README.md中有说明源码是基于Delphi 10.2.1版本的，所以你这10.1的比现有低有些属性不存在很正常，如果不想使用10.2.1的就得自己处理下这些错误，可以删除或者是修改。
