### ISSUE TITLE
Help, windows下窗口字体乱码

### ISSUE THREAD

**Issue by huapox** [ying32/govcl#37]
![2019-12-19_224203](https://user-images.githubusercontent.com/6138651/71182388-fba98200-22b0-11ea-8ecd-1ecb2338cc4f.png)

**Comment by huapox** [comment]
![2019-12-19_224410](https://user-images.githubusercontent.com/6138651/71182552-390e0f80-22b1-11ea-840c-4be9383a0226.png)

`vcl.ShowMessage("连接服务器失败，错误：" + err.Error())`这个是正常的， 进入窗口就不行了

**Comment by ying32** [comment]
看你输出的提示用了旧版本的代码和预编译库。将govcl和对应的二进制更新到最新

**Comment by huapox** [comment]
多谢，之后试试

**Comment by huapox** [comment]
![libvcl_ok](https://user-images.githubusercontent.com/6138651/71446732-7c5cf800-2761-11ea-9b33-7a0f00b56d55.png)

**Comment by ying32** [comment]
govcl的源码用master分支的，如果用到了lazarus设计界面的话，保持res2go为最新（当前为1.0.16），那个资源文件的生成可以在wiki中找到生成方法

**Comment by huapox** [comment]
> 你的乱码问题还是之前那样么？如果不是的话且如果用到了lazarus设计界面的话，保持res2go为最新（当前为1.0.16），那个资源文件的生成可以在wiki中找到生成方法

感谢回复。

- 使用liblcl的话(下载的libclc)，与原来一样的乱码(原来liblcl lazarus自行编译的)。
- 资源文件的生成可以在wiki中暂未找着， https://gitee.com/ying32/govcl/wikis/Icon及manifest文件集成?sort_id=410058 这个？ 不是很确定..
- res2go先前未用过，这个是从delphi/lazarus项目转窗体才用到吧。（我下载直接双击生成了 defaultRes_windows.syso 替换到sample中，发现与sample内容是一样的，[git显示无变化]）

**Comment by ying32** [comment]
1、你现在用的go的哪个版本啊，最近有对于这个修复过。有没有用go.mod，这个可能影响pull问题。    
2、就是这个，这个是教你手动生成自己需求的syso文件。    
3、默认生出来的这个syso文件是我内置的，仅用来测试的，具体的需要根据自己的需求来生成。

**Comment by huapox** [comment]
> 1、你现在用的go的哪个版本啊，最近有对于这个修复过。有没有用go.mod，这个可能影响pull问题。

- go版本 `1.13.5 `
- 单个main.go文件我这一般直接go run main.go
- 带窗体的sample, 先`go mod init xxx`， 再用`go build .` 生成 
  - 不用它 直接go run发现带窗体的form对应的依赖加载不上。 
  - 我在windows试其它项目可以直接go run。
