### ISSUE TITLE
没有选择目录对话框, 而且打开文件对话框不能多选文件

### ISSUE THREAD

**Issue by javarobot234** [ying32/govcl#39]
win7 64

TSelectDirectoryDialog 这个没实现
OpenDialog.SetOptions(types.OfAllowMultiSelect) 这个无效

**Comment by ying32** [comment]
* 1、系统对话框的，请参考[samples/sysdialog](https://github.com/ying32/govcl/tree/master/samples/sysdialog)例子。
* 2、`TSelectDirectoryDialog`这个组件没啥必要，有替代的API`vcl.SelectDirectory1`,`vcl.SelectDirectory2`  。
* 3、这个无效是你使用错误，`SetOptions`的参数为一个集合类型
```go
// 添加选项
OpenDialog.SetOptions(rtl.Include(OpenDialog.Options(), types.OfAllowMultiSelect))
// 减去选项
OpenDialog.SetOptions(rtl.Exclude(OpenDialog.Options(), types.OfAllowMultiSelect))
```
* 4、如何确认参数类型是一个集合类型，请跳转到类型定义处，参见注释是否为`type = set of xxx`其定义为`type xxx = uint32`，集合类型定义的为`uint32`类型别名。

**Comment by javarobot234** [comment]
虽然提问前搜索了代码的dialog关键字 可惜没找到相关信息... 
谢谢热心解答
