### ISSUE TITLE
Is it possible to change LGPL to more permissive license ?

### ISSUE THREAD

**Issue by RadhiFadlillah** [ying32/govcl#4]
Hi @ying32, thanks for this awesome library. 

I've been looking for simple GUI library for Golang, and I think this library matches my requirement. However, I noticed that you use LGPL-2 as the license for this library.

As far as I know, LGPL license insists that end user must be able to recombine or relink the application with a modified or different version of the LGPL library. However, Golang as today only support static linking the library.

That means, if I use this library for my Golang project, I can't create a closed source application, because according to LGPL the end user **must** be able to swap the LGPL library with other version that he wants. And since Golang still not supporting dynamic linking, my only choice is to give the end user my source code, so he can compile it with his own library.

You can see more details about implication of using LGPL license in Golang project [here](https://github.com/therecipe/qt/wiki/FAQ#what-is-the-implication-from-using-lgpl-library-in-my-go-app-).

So, is it possible for you to change the LGPL license to more permissive license ? Maybe for example you can use [MIT License](https://tldrlegal.com/license/mit-license), [Apache 2.0](https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)) or [BSD 3.0](https://tldrlegal.com/license/bsd-3-clause-license-(revised)). I personally recommended Apache 2.0 which allows the programmer to use your library however he/she want, as long as he/she gives proper attribution to you as the creator of this library.

Thank you.

**Comment by ying32** [comment]
Hi RadhiFadlillah
I have changed the "govcl" license to [Apache License 2.0](https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)).

**Comment by RadhiFadlillah** [comment]
@ying32 thank you very much.

By the way, do you mind if I write the wiki for English language ? If it's OK with you, I will start working on it later today.

**Comment by ying32** [comment]
of course. thank you very much.
