### ISSUE TITLE
rtl.SysOpen

### ISSUE THREAD

**Issue by wolf-leo** [ying32/govcl#42]
无法打开二级目录

Win:
rtl.SysOpen("F:\\") 可以打开
rtl.SysOpen("F:\\filename\\") 不可以打开

**Comment by ying32** [comment]
```go
// windows下没问题
rtl.SysOpen("F:\\filename\\")
```

**Comment by wolf-leo** [comment]
> ```go
> // windows下没问题
> rtl.SysOpen("F:\\filename\\")
> ```

发现了 带中文的二级目录就打不开

**Comment by ying32** [comment]
试了下，确实是个bug，SysOpen在Windows下内部是用的ShellExecute，你以自己调用下，在win包里有这个函数
