### ISSUE TITLE
ListBox的ScrollBy方法没有效果呀

### ISSUE THREAD

**Issue by zs5460** [ying32/govcl#45]
我想添加行到ListBox后自动滚动到最下面，用ScrollBy方法完全不动呀

**Comment by ying32** [comment]
> 我想添加行到ListBox后自动滚动到最下面，用ScrollBy方法完全不动呀

listbox.Items().Add("111")
listbox.SetItemIndex(listbox.Items().Count()-1)

**Comment by zs5460** [comment]
果然可以，谢谢！
