### ISSUE TITLE
我程序要管理员权限，所以程序目录添加了nac.syso，但是提示 too many .rsrc sections

### ISSUE THREAD

**Issue by 308066400** [ying32/govcl#47]
github.com/ying32/govcl/pkgs/winappres(.rsrc): too many .rsrc sections

如何优雅地解决这个问题？

肯定管理员权限的，肯定不去动注册表之类的。

**Comment by ying32** [comment]
![image](https://user-images.githubusercontent.com/7037165/92586800-54023300-f2c9-11ea-9379-0b347a9ed6a4.png)
仔细看红框内注释。
