### ISSUE TITLE
按钮是否可以修改背景颜色的，自定义文字

### ISSUE THREAD

**Issue by zj360202** [ying32/govcl#48]
目前几种按钮要么只能支持背景，无法设置文字；要么文字与颜色分开的(左右上下)。需要文字是输入的，背景是通过图片或颜色进行设定的按钮，是否可以支持下，非常感谢！！

**Comment by ying32** [comment]
可以看下`TXButton`，如果都不能满足你就没。

**Comment by zj360202** [comment]
确认了，可以满足需求，非常感谢
