### ISSUE TITLE
label设定固定宽度后，文字是否可以相对于label设置左右上下对齐？

### ISSUE THREAD

**Issue by zj360202** [ying32/govcl#49]
目前多个label右对齐非常不方便，不知道是否可以支持

**Comment by ying32** [comment]
源码中的大多数属性都有注释：   
`SetAlignment` 文字水平： 左对齐、居中对齐，右对齐。   
`SetLayout` 文字垂直对齐：上、 中、 下。

**Comment by zj360202** [comment]
感谢，确认好用！！！
