### ISSUE TITLE
how to access style files for sample "style"

### ISSUE THREAD

**Issue by ffred60** [ying32/govcl#5]
Hi,
first, thanks for your work. just discovered it and looks great !

now, in the readme of "style" sample there's a link to download style files, but it's on a Chinese website witch - I think - ask me to register. 
can't you put the files on the same place as the vcl & lcl libraries so we can directly have access ?
thanks

**Comment by ying32** [comment]
Hi ffred60!
Of course, but now I have something to do. I can't do this for a while.

**Comment by ffred60** [comment]
no problem, I'm just looking inside govcl and try to understand how to work with it. 
no need to rush.
thanks..

**Comment by ying32** [comment]
Hi!  
I have uploaded VCL Style files.  
[![VCL style files](https://img.shields.io/badge/downloads-VCL%20style%20files-blue.svg)](https://github.com/ying32/govcl/releases/download/v1.1.20/vcl-styles.zip)
