### ISSUE TITLE
窗体是否可以设置边框不能随意拉伸

### ISSUE THREAD

**Issue by zj360202** [ying32/govcl#50]
窗体在设计好内容后，还是可以随便拖拉边框，显示一些框外区域。测试过SetScaled, SetEnabled, SetAutoSize, SetDockSite等，都不管用。
       不确定是我使用方法不正确还是暂时没有支持，劳烦指点下。感谢感谢！！！

**Comment by ying32** [comment]
设置边框样式为bsSingle……

**Comment by zj360202** [comment]
已经解决，主要是用例中，比较好的，几乎都是lazarus实现的，很多的一些内容，无法看到实现过程，所以使用过程有很多不理解的，劳烦大佬了
