### ISSUE TITLE
关闭按钮加提示窗口无法生效？

### ISSUE THREAD

**Issue by zj360202** [ying32/govcl#51]
`       mainForm.SetOnClose(func(sender vcl.IObject, action *types.TCloseAction) {
		fmt.Println("close main form")
		CloseApp.Show()
		mainForm.Hide()
	})`
        `mainForm.SetOnDestroy(func(sender vcl.IObject) {
		fmt.Println("destory main form")
	})
`
关闭窗口的时候，我确定走了上述两个方法，但是CloseApp窗口还是没有显示出来就服务器停止了
并且此closeApp窗口，我在其他按钮上面测试，是可以正常显示的。
劳烦大佬了！！！

**Comment by ying32** [comment]
例子里有用OnCloseQuery事件就是了……

**Comment by zj360202** [comment]
还是直接关闭
mainForm.SetOnCloseQuery(func(sender vcl.IObject, canClose *bool) {
		fmt.Println("close query main form")
		CloseApp.Show()
	})
打印会显示，但是没有弹出窗口就关闭了

**Comment by ying32** [comment]
多看看例子。。里面有。

**Comment by zj360202** [comment]
mainForm.SetOnCloseQuery(func(Sender vcl.IObject, CanClose *bool) {
	*CanClose = vcl.MessageDlg("是否退出？", types.MtConfirmation, types.MbYes, types.MbNo) == types.IdYes
})
解决
