### ISSUE TITLE
SetOnMouseWheelDown与SetOnMouseWheelUp怎么获取滚动的次数

### ISSUE THREAD

**Issue by zj360202** [ying32/govcl#53]
f.SetOnMouseWheelDown(func(sender vcl.IObject, shift types.TShiftState, mousePos types.TPoint, handled *bool) {
	fmt.Println("mouse wheel down:", mousePos.X, mousePos.Y, *handled, shift)
})
f.SetOnMouseWheelUp(func(sender vcl.IObject, shift types.TShiftState, mousePos types.TPoint, handled *bool) {
	fmt.Println("mouse wheel up:", mousePos.X, mousePos.Y, *handled, shift)
})
mouse wheel down: 63 49 false 0
mouse wheel up: 49 52 false 0
好像没有无法获取向上或向下滚动的次数

**Comment by ying32** [comment]
`OnMouseWheel`，`wheelDelta`参数，，另外这不是滚动次数吧。。。

**Comment by zj360202** [comment]
我的意思是，是否可以通过上面的两个监听函数(或是其他的监听函数)，获取鼠轮的参数，主要是滚动的次数

**Comment by ying32** [comment]
我上面不是回答你了么。。。

**Comment by zj360202** [comment]
f.SetOnMouseWheel(func(sender vcl.IObject, shift types.TShiftState, wheelDelta, x, y int32, handled *bool) {
	fmt.Println("mouse wheel:", wheelDelta, x, y, *handled, shift)
})
mouse wheel: 120 44 62 false 0
mouse wheel: -120 44 62 false 0
测试过了，可以的，上面没有看懂意思，抱歉了
