### ISSUE TITLE
如果想要不断的显示新的图像，应该用哪个组件比较合适啊

### ISSUE THREAD

**Issue by zj360202** [ying32/govcl#55]
我现在使用的是
f1, _ := os.Open("3.bmp")
defer f1.Close()
img1, _ := ioutil.ReadAll(f1)
f.img = vcl.NewImage(f)
f.img.SetAutoSize(true)
mem1 := vcl.NewMemoryStream()
defer mem1.Free()
mem1.Write(img1)
mem1.SetPosition(0)
f.img.Picture().LoadFromStream(mem1)
f.img.SetParent(f)

f.img.SetOnClick(func(sender vcl.IObject) {
------changeImg(f)
})
////////////////////
func changeImg(f *TMainForm)  {
------fmt.Println("change img")
------f1, _ := os.Open("3.bmp")
------f2, _ := os.Open("4.bmp")
------defer f1.Close()
------defer f2.Close()
------img1, _ := ioutil.ReadAll(f1)
------img2, _ := ioutil.ReadAll(f2)
------mainForm.img = vcl.NewImage(f)
------mainForm.img.SetAutoSize(true)
------mem1 := vcl.NewMemoryStream()
------defer mem1.Free()
------mem1.Write(img1)
------mem1.SetPosition(0)
------mem2 := vcl.NewMemoryStream()
------defer mem2.Free()
------mem2.Write(img2)
------mem2.SetPosition(0)
------mainForm.img.Picture().LoadFromStream(mem1)
------for i:=0; i<10;i++{
------------fmt.Println("load img ...", i)
------------if i%2==0{
------------------mainForm.img.Picture().LoadFromStream(mem1)
------------}else{
------------------mainForm.img.Picture().LoadFromStream(mem2)
------------}
------}
}
但是发现后续不能修改图像，会报错unknown picture format

**Comment by zj360202** [comment]
------start_time := time.Now().Nanosecond() / 1e6
------for i:=0; i<10;i++{
------------fmt.Println("load img ...", i, i%2)
------------mem1 := vcl.NewMemoryStream()
------------defer mem1.Free()
------------//p := vcl.NewPicture()
------------if i%2==0{
------------------mem1.Write(img1)
------------------mem1.SetPosition(0)
------------------//p.LoadFromStream(mem1)
------------------//mainForm.img.SetPicture(p)
------------------f.img.Picture().LoadFromStream(mem1)
------------}else{
------------------mem1.Write(img2)
------------------mem1.SetPosition(0)
------------------//p.LoadFromStream(mem2)
------------------//mainForm.img.SetPicture(p)
------------------f.img.Picture().LoadFromStream(mem1)
------------}
------}
------fmt.Println("spend time", (time.Now().Nanosecond()/1e6)-start_time)
现在可以图片不报错了 ，但是中间切换的过程不知道是太快了，还是怎么地，没有显示，只有最后一次变化显示了，
显示10张图片，开销500ms，感觉好像有点慢，图像尺寸是1920x1080的，应该是在men1.write(img1)的时候开销比较大

**Comment by zj360202** [comment]
是否有其他的组件也可以实现的，我可以自己试下是否可以快一点
当前的情况说明一下，截屏是60ms, 图像分析压缩与传输合并解析<100ms，所以希望能实现一个展示<50ms以内的，最后10ms左右的
谢谢

**Comment by ying32** [comment]
这么大的图片，还从文件加载，哪有开销不大的呢。。 自己要想办法全内存操作，做好双缓冲，或者考虑自己绘制呗。。。

**Comment by zj360202** [comment]
抱歉，上面没有描述的特别清楚，后来我在多测试了几下，现在我觉得可以说的更准确一点了。
1. 
mem1 := vcl.NewMemoryStream()
defer mem1.Free()
mem1.Write(img1)
mem1.SetPosition(0)
上述只要5ms完成
f.img.Picture().LoadFromStream(mem1)  这个需要250ms
上面的测试，我认为可能是NewMemoryStream的接口是静态加载，要等调用的时候才真正加载，所以我有找到了一个方法
2.
a:=vcl.NewMemoryStreamFromBytes(img1)
defer a.Free()
a.SetPosition(0)
f.img.Picture().LoadFromStream(a)
这个和上面的结果是一样的，
而测试过程中f.img.Picture()就只有两种加载图片的方式，一个就是LoadFromStream，另一个是LoadFromFile，而LoadFromStream的数据来源有只有上面的两种方式；
当前，SetPicture我也测试了，最后的数据来源还是BitMap.LoadFromStream, 所以最终的时间开销非常大
我这里的问题是：
1. 怎样操作才能提前将测试数据已经在内存中，因为上的img1是[]byte类型，我的理解已经加载到内存了，所以后续的操作应该已经是对内存操作，我上面的时间并不包含os.open与ioutils.readall的时间
2. 是否有其他的类型timage的也可以显示图片，具体效果我可以测试，我在组件找不到可以显示图片的插件，也使用了larazus工具看了下，的确没有看到理想的，也许是我不会使用导致没有找到。

**Comment by zj360202** [comment]
您好，
我测试了下，发现了canvas可以做到极致，画10次只需要180ms左右；
但是好像有一个问题，就是需要在SetOnPaint中才能有效，放在外面是无效的，而且触发情况是更改窗体大小的时候触发，目前没有发现是否有其他情况触发？
如果在图像内容有改变的时候也可以触发，应该就OK了。-----已经测试，会触发；问题到此结束，感谢支持
f1, _ := os.Open("3.bmp")
defer f1.Close()
b1, err := bmp.Decode(f1)
if err != nil{
------fmt.Println("bmp decode fail:", err)
}
b := vcl.NewBitmap()
err =bitmap.ToBitmap2(b1, b)
if err != nil{
------fmt.Println("bitmap :", err)
}
fmt.Println("ready to draw ")

index := 0
f.SetOnPaint(func(sender vcl.IObject) {
------f.canvas  = f.Canvas()
------f.canvas.Draw(0, 0, b)
------changeImg(f, &index) // 画10次图像
------index ++
})
// 新加测试，可以在等待1s后修改图像，图像会被修改，时间约在20ms以内，而且理论上支持局部修改，目前还没有测试，此issue就到此结束了
go testChange(f)

**Comment by ying32** [comment]
你改变了Repaint下不就可以了么。。。
