### ISSUE TITLE
在线程中，有什么办法或事件可以通知到主线程的UI进行展示/隐藏吗

### ISSUE THREAD

**Issue by zj360202** [ying32/govcl#57]
我尝试过，在线程中repaint是不行的，但是也不能让主线程死循环监听一个东西，是否有哪个监听事件，是可以代码触发主线程的监听事件

**Comment by ying32** [comment]
仔细阅读文档的“重要提醒”或者"README_zh-CN.md"中最后的“提醒”。

**Comment by zj360202** [comment]
解决了，谢谢！
