### ISSUE TITLE
govcl怎么修改生产的exe图标啊，用syso的方式改变不了

### ISSUE THREAD

**Issue by zj360202** [ying32/govcl#59]
我使用windres创建了main.syso，与main.go放在同级目录，创建的时候，却改变了生成的exe图标？
对于简单项目创建的exe，用上述通用的方式，确实可以改的，我使用的脚本是通过lazarus输出的脚本
go build -i -buildmode=exe -ldflags="-H windowsgui -w -s" -o "D:\workspace\lazarus\test\test.exe": Success

测试testVCL
go build -i -buildmode=exe -ldflags="-H windowsgui -w -s" -o "main.exe" main.go
go build -i -buildmode=exe -ldflags="-H windowsgui -w -s" -o "main.exe"
上述无法正确创建
都是闪现一个自定义ico图标的情况，然后就被默认govcl的图标覆盖了

**Comment by ying32** [comment]
参考[Icon及manifest文件集成](https://gitee.com/ying32/govcl/wikis/pages?sort_id=410058&doc_id=102420)，如不行，请自行查找自己的原因。

**Comment by zj360202** [comment]
确认了，直接注释  //_ "github.com/ying32/govcl/pkgs/winappres"，就可以了
也许是我们看到你的说明，上面写的
注：一个go工程中，只能有一个.syso文件，如果采用自定义的，则不能再导入winappres包
不知道是否就是这个意思。
