### ISSUE TITLE
TStringList无法获取插入的Object

### ISSUE THREAD

**Issue by ismlsmile** [ying32/govcl#6]
调用TStringList的AddObject方法插入对象后，再调用Objects方法获取刚才插入的对象，返回值为空，测试代码：

package main

import (
	"gitee.com/ying32/govcl/vcl"
	"unsafe"
)

type Person struct {
	Name string
}

func main() {
	p1 := &Person{}
	p1.Name = "Tom"

	strList := vcl.NewStringList()
	strList.AddObject("item1", vcl.ObjectFromInst(uintptr(unsafe.Pointer(&p1))))

	item1 := (* Person)(unsafe.Pointer(strList.Objects(0)))
	println("Name = " + item1.Name)
}

**Comment by ying32** [comment]
我修改了下，这样写才对，有可能被GC
```go
package main

import (
	"unsafe"

	"github.com/ying32/govcl/vcl"
)

type Person struct {
	Name string
}

func main() {
	// 这里已经是指针了
	p1 := &Person{}
	p1.Name = "Tom"

	strList := vcl.NewStringList()
        // 要记得添加内存释放的
	defer strList.Free()
	// 这里直接使用
	strList.AddObject("item1", vcl.ObjectFromInst(uintptr(unsafe.Pointer(p1))))

	// 这里要获取指针的实例地址
	item1 := (*Person)(unsafe.Pointer(strList.Objects(0).Instance()))
	println("Name = " + item1.Name)

}
```

**Comment by ismlsmile** [comment]
前面我的测试代码有个笔误：
strList.AddObject("item1", vcl.ObjectFromInst(uintptr(unsafe.Pointer(&p1))))

后面取了指针的指针，所以怎么试都崩溃，用上面你改的示例可以运行。

但拿到事件回调函数中获取就不行了，应该是被gc了。可能需要类似ListView和TreeView那样的改造。

**Comment by ying32** [comment]
你检出下dev分支的代码，然后这样写个看看
```go
package main

import (
	"unsafe"
	"github.com/ying32/govcl/vcl"
)

type Person struct {
	Name string
}

func main() {
	// 这里已经是指针了
	p1 := &Person{}
	p1.Name = "Tom"

	strList := vcl.NewStringList()
        // 要记得添加内存释放的
	defer strList.Free()
	// 这里直接使用
	strList.AddObject("item1", vcl.ObjectFromUnsafePointer(unsafe.Pointer(p1)))

	item1 := (*Person)(strList.Objects(0).UnsafeAddr())
	println("Name = " + item1.Name)

}
```

**Comment by ismlsmile** [comment]
checkout了dev分支测试了一下，上面的代码运行OK。在事件回调中测试也OK，完美！

**Comment by ying32** [comment]
哈哈，遇到GC上面的代码也不知道会有不会啥意外的
