### ISSUE TITLE
如果希望多个窗口，最小化与正常显示，完全独立，而不是最小化全部最小化怎样实现

### ISSUE THREAD

**Issue by zj360202** [ying32/govcl#60]
目前所有窗口是随着主窗口的最小化，而全部最小化的；是否可以独立显示？

**Comment by ying32** [comment]
有些特殊的的东西没办法导出来，所以弄出来的效果不好。算是没好办法了。

**Comment by zj360202** [comment]
好的，非常感谢！！！非常期待！！！

**Comment by ying32** [comment]
* 1、更新govcl代码到 v2.0.9
* 2、下载最新版本的liblcl二进制
* 3、参考例子[createparams](https://github.com/ying32/govcl/tree/master/samples/Windows/createparams)。

**Comment by zj360202** [comment]
太好了
