### ISSUE TITLE
如果希望多个窗口，最小化与正常显示，完全独立，linux与mac可以实现吗

### ISSUE THREAD

**Issue by zj360202** [ying32/govcl#62]
如果希望多个窗口，最小化与正常显示，完全独立，而不是最小化全部最小化怎样实现
此功能在win上面好使，是否可以在linux与mac上面也可以实现

**Comment by ying32** [comment]
不知道，对linux跟mac不熟。。。。这个只能你自己找找其他的看看了

**Comment by zj360202** [comment]
好的
