### ISSUE TITLE
创建CheckListBox 会弹窗报错 Access violation. Press OK to ignore and risk data corruptio. Press Abort to kill the program.

### ISSUE THREAD

**Issue by xhaoh94** [ying32/govcl#63]

**Comment by xhaoh94** [comment]
程序启动警告缺少proc "SetRequestCallCreateParamsCallback" not find. 
创建非主窗口警告缺少proc "Form_SetGoPtr" not find.
创建CheckListBox 会弹窗报错 Access violation. Press OK to ignore and risk data corruptio. Press Abort to kill the program.

**Comment by xhaoh94** [comment]
警告那个，更换了最新liblcl.dll搞定了

**Comment by ying32** [comment]
如果你用的go>=1.15，参考 [重要提醒](https://gitee.com/ying32/govcl/wikis/pages)

**Comment by xhaoh94** [comment]
如果你用的go>=1.15，参考 重要提醒
