### ISSUE TITLE
希望可以得到shell32dll中的SHGetFileInfoW，可以自己添加吗

### ISSUE THREAD

**Issue by zj360202** [ying32/govcl#64]
我这边已经测试了过了调取的方式， 可以提交PR吗

`
import (
	"golang.org/x/sys/windows"
	"syscall"
	"unsafe"
)
type HANDLE uintptr
type HICON HANDLE
const MAX_PATH = 260
type SHFILEINFO struct {
	HIcon         HICON
	IIcon         int32
	DwAttributes  uint32
	SzDisplayName [MAX_PATH]uint16
	SzTypeName    [80]uint16
}
var{
    shell32dll = syscall.NewLazyDLL("shell32.dll")
    _SHGetFileInfo  = shell32dll.NewProc("SHGetFileInfoW")
}
func SHGetFileInfo(pszPath uintptr, dwFileAttributes uint32, psfi *SHFILEINFO, cbFileInfo, uFlags uint32) uintptr {
	r, _, _ := _SHGetFileInfo.Call(pszPath, uintptr(dwFileAttributes), uintptr(unsafe.Pointer(psfi)), uintptr(cbFileInfo), uintptr(uFlags),)
	return r
}

samples
                testPath1 := utf16.Encode([]rune("C:\\Users\\Public\\Desktop\\CMake (cmake-gui).lnk"))
		var testPath [MAX_PATH]uint16
		for i:=0; i<len(testPath1);i++{
			if i < MAX_PATH{
				testPath[i] = testPath1[i]
			}
		}
                b:=SHGetFileInfo1(uintptr(unsafe.Pointer(&testPath[0])), 0, &shFileInfo, uint32(unsafe.Sizeof(shFileInfo)), 0x000000100|0x000000200|0x000000400|0x000001000|0x000004000)
		fmt.Println(b)
		fmt.Println(shFileInfo.IIcon)
`

**Comment by ying32** [comment]
这个我自己来就行了。。 其实这些可以自己申明，不一定要合并进来的

**Comment by zj360202** [comment]
好的，主要是希望直接统一在一个地方管理
