### ISSUE TITLE
miniwebview加载页面后，关闭窗口会卡死

### ISSUE THREAD

**Issue by trying2016** [ying32/govcl#66]
在windows上测试，用samples中的miniwebview加载网页后，关闭窗口，会导致程序卡死，程序不能退出

**Comment by ying32** [comment]
网页链接多少，什么系统运行的，liblcl版本多少

**Comment by trying2016** [comment]
操作系统：win10
版本：2.0.9
地址：www.baidu.com

**Comment by ying32** [comment]
我也是win10也是百度，没这问题啊
