### ISSUE TITLE
ShowMessage如何替换图标

### ISSUE THREAD

**Issue by anhoder** [ying32/govcl#68]
我已经给vcl.Application设置了Icon，但是ShowMessage的Icon还是默认的图标
![image](https://user-images.githubusercontent.com/27605589/108312388-a0935800-71f1-11eb-919a-d5b811f2eca0.png)

**Comment by ying32** [comment]
MacOS下机制不同……得改变应用程序图标，而不是设置这个

**Comment by anhoder** [comment]
你说的应用程序图标是指这个吗
![image](https://user-images.githubusercontent.com/27605589/108341331-8454e280-7214-11eb-98dc-2c79b3682ec1.png)

**Comment by ying32** [comment]
额
