### ISSUE TITLE
go1.16版本, 报错 panic: Failed to load liblcl.dll: The specified module could not be found. 

### ISSUE THREAD

**Issue by j787701730** [ying32/govcl#69]
使用go mod模式, go版本: 1.16
panic: Failed to load liblcl.dll: The specified module could not be found.

goroutine 1 [running]:
github.com/ying32/govcl/vcl/api.loadUILib(0xf006e0)
	C:/Users/aoc/go/pkg/mod/github.com/ying32/govcl@v2.0.9+incompatible/vcl/api/dylib_nonmemory.go:32 +0x173
github.com/ying32/govcl/vcl/api.init()
	C:/Users/aoc/go/pkg/mod/github.com/ying32/govcl@v2.0.9+incompatible/vcl/api/dylib.go:19 +0x145

**Comment by ying32** [comment]
请仔细阅读README-zh_CN.md或者文档中的入门。
