### ISSUE TITLE
Difficulties in getting it to work on macOS

### ISSUE THREAD

**Issue by carlca** [ying32/govcl#7]
Hello, As someone with 20 year's experience of Delphi (and more recently Free Pascal/Lazarus) and also a Golang user for the last year, I am naturally very interested in this project.

However, I am having difficulties following the exact steps needed to run it on macOS. Could you set out some step by step instructions that would guarantee that I would be able to build and install this package? 

I realise and appreciate that English is not your native language, but at the moment there are too many missing gaps in the instructions, which leaves too much to guesswork. 

If you can do this for me, I will definitely do all I can to promote it! 

Thanks in advance,
Carl

**Comment by ying32** [comment]
Hi!  
You can import the "github.com/ying32/govcl/vcl/exts/tools" package and then  
```go
func main() {
    // Official release please remove
    tools.RunWithMacOSApp()
    ...
    ...
}
```
Copy "liblcl.dylib" to the "your.app/Contents/MacOS/" directory.    

Will optimize application packaging under MacOS in the future.

**Comment by carlca** [comment]
Hello, I've used this app https://github.com/machinebox/appify to generate an `.app` package. I then placed "liblcl.dylib" in the MacOS folder of my `.app` file.

I tried to run the app but nothing seemed to happen. Debugging within VSCode seems to suggest that the app is bailing out within the `tools.RunWithMacOSApp()` function...

![screen shot 2018-08-08 at 10 58 31](https://user-images.githubusercontent.com/260612/43831015-b5286196-9afa-11e8-80c0-0e6c8fdb5d90.png)

Any ideas?

Cheers,
Carl

**Comment by ying32** [comment]
Hi!
If you use the "appify" tool, don't use the "tools.RunWithMacOSApp" function. Copy liblcl.dylib directly to the "your.app/Contents/MacOS/" directory.

**Comment by carlca** [comment]
Hello again. Thanks for the reply! 

I created a `.app` without the `tools.RunWithMacOSApp()` and this time the debug managed to get all the way through without crashing. 

However, the debug console still shows multiple entries with `dlsym err: invalid handle passed to dlsym()`. 

And the application didn't appear to run.

**Comment by ying32** [comment]
liblcl.dylib is a 32bit shared library, If your VSCode is 64bit, it can't be debugged.

**Comment by carlca** [comment]
I can live without the debugging. But when I simply double click on the app file the app doesn't appear to start.

**Comment by ying32** [comment]
GOARCH must be 386 because liblcl.dylib is a 32bit shared library.  

The error of `"dlsym err: invalid handle passed to dlsym()"` basically shows that you are using a 64bit program to load a 32bit shared library.

**Comment by carlca** [comment]
Thanks for the continued help! I've tried using `GOARCH=386 go build main.go` but this gives me...
```
/Users/carlca/Code/go/src/github.com/ying32/govcl/vcl/api/dylib.go:27:19: undefined: dylib.LazyDLL
/Users/carlca/Code/go/src/github.com/ying32/govcl/vcl/api/dylib.go:45:9: undefined: dylib.NewLazyDLL
/Users/carlca/Code/go/src/github.com/ying32/govcl/vcl/api/dylib.go:51:9: undefined: dylib.NewLazyDLL
```

**Comment by ying32** [comment]
I wrote a simple program, compiled and packaged, and there is source code.
[vcltest.zip](https://github.com/ying32/govcl/files/2273392/vcltest.zip)

**Comment by carlca** [comment]
Hello! Thank for your patience! The vcltest app works! As expected, it gave me a message about the app needing upgrading by the developer, which I believe is because it's a 32-bit app.

It does beg the question of why my attempts to build using `GOARCH=386 go build main.go` failed. Any ideas about that?

**Comment by ying32** [comment]
`
GOARCH=386
GOOS=darwin
CGO_ENABLED=1
`
Set the above environment variables and then compile.

**Comment by carlca** [comment]
Yes! That works perfectly! Thanks so much for your help, it's very much appreciated.

**Comment by carlca** [comment]
One other question, if I may. Were you able to use LiteIDE to debug VCLGo apps as 32 bit?

**Comment by ying32** [comment]
It should be ok, but I haven't tried. I usually just compile with liteIDE under MacOS
