### ISSUE TITLE
trayicon例子中, mainForm.Hide()后再mainForm.Show(), 只会在任务栏显示, 不会弹出窗口

### ISSUE THREAD

**Issue by j787701730** [ying32/govcl#70]
trayicon例子中, 最小化事件mainForm.Hide()后, 再mainForm.Show(), 只会在任务栏显示, 不会弹出窗口. 我是想弹出窗口了, win10系统. 先谢谢大家解答.

**Comment by ying32** [comment]
看那个事件中的注释写的啥。

**Comment by j787701730** [comment]
// Windows上为了最前面显示，有时候要调用SetForegroundWindow
// 比如：win.SetForegroundWindow(mainForm.Handle())
去掉注释也没用了,  还是只是在任务栏显示, 不会弹出窗口, 要在点任务栏才会弹出窗口. 是因为hide()是隐藏和最小化两种效果? 而show()只是显示, 没有还原窗口功能. 感谢@ying32

**Comment by j787701730** [comment]
![image](https://user-images.githubusercontent.com/23625690/108953186-c020f980-76a5-11eb-8ea1-8e2cf906e6bf.png)
只会这样, 不会弹出窗口.

**Comment by j787701730** [comment]
![image](https://user-images.githubusercontent.com/23625690/108953359-09714900-76a6-11eb-87b8-79eb303a0b3e.png)
我是go 1.16版本.

**Comment by ying32** [comment]
再加一句，或者不要SetForegroundWindow，换成vcl.Application.Restore

**Comment by j787701730** [comment]
@ying32 可以了. 谢谢指导.
