### ISSUE TITLE
按DEMO 操作后，没有出现预期的表单及按钮。

### ISSUE THREAD

**Issue by Joe3160** [ying32/govcl#71]
运行后 输出效果：
Library Version: 2.0.9
libpng warning: iCCP: cHRM chunk does not match sRGB

![image](https://user-images.githubusercontent.com/20843447/109445277-36dd3e80-7a7a-11eb-9e20-c75137ee22dc.png)

环境信息：
liblcl-2.0.9
go version go1.15.5 windows/amd64

**Comment by ying32** [comment]
大哥，你发个空窗口，也没说用啥控件啊，我也猜不到啊。。。 
另一个信息看着像是不支持sRGB色的png吧。。。你可以弄成rgb色的啊。。。

**Comment by Joe3160** [comment]
> 大哥，你发个空窗口，也没说用啥控件啊，我也猜不到啊。。。
> 另一个信息看着像是不支持sRGB色的png吧。。。你可以弄成rgb色的啊。。。
```golang
package main


import (
    // 如果你使用自定义的syso文件则不要引用此包
    _ "github.com/ying32/govcl/pkgs/winappres"
    "github.com/ying32/govcl/vcl"
)

type TMainForm struct {
    *vcl.TForm
    Btn1     *vcl.TButton
}

type TAboutForm struct {
    *vcl.TForm
    Btn1    *vcl.TButton
}

var (
    mainForm *TMainForm
    aboutForm *TAboutForm
)

func main() {
    vcl.Application.Initialize()
    vcl.Application.SetMainFormOnTaskBar(true)
    vcl.Application.CreateForm(&mainForm)
    vcl.Application.CreateForm(&aboutForm)
    vcl.Application.Run()
}

// -- TMainForm

func (f *TMainForm) OnFormCreate(sender vcl.IObject) {

}

func (f *TMainForm) OnBtn1Click(sender vcl.IObject) {
    aboutForm.Show()
}

// -- TAboutForm

func (f *TAboutForm) OnFormCreate(sender vcl.IObject) {

}

func (f *TAboutForm) OnBtn1Click(sender vcl.IObject) {
    vcl.ShowMessage("Hello!")
}
```

**Comment by ying32** [comment]
大哥，你这能有按钮就有鬼了啊，参考[初次使用步骤](https://gitee.com/ying32/govcl/wikis/%E5%88%9D%E6%AC%A1%E4%BD%BF%E7%94%A8%E6%AD%A5%E9%AA%A4?sort_id=1540640)，你这明显示是`方法一`的，方法一后面写了说明。。。。   
![image](https://user-images.githubusercontent.com/7037165/109623435-1b585d80-7b78-11eb-8869-a7830849781d.png)
