### ISSUE TITLE
NewLabel文字能居右? 

### ISSUE THREAD

**Issue by j787701730** [ying32/govcl#72]
作者你好, 感谢你的项目. 
我是写过html和flutter的, 能否借鉴下布局.  
比如:
style := canvas.Font().Style()
canvas.Font().SetStyle(style.Include(types.FsBold, types.FsItalic)). 个人感觉有点复杂, 要看例子才行. 
![image](https://user-images.githubusercontent.com/23625690/109625980-edc0e380-7b7a-11eb-8ec9-9c0fd9809514.png)
这种多行多列的用什么组件布局比较好, 我当前是使用计算top和left来做的. 望大神们指点. [感谢]

**Comment by ying32** [comment]
我明明记得我回复了的，竟然没回复成功。。。。。
可以考虑用TListView，可能不是特别好看，列上会有分割线，或者考虑用TStringGrid，修改相关属性可以去掉一些线条等等之类的，效果会比TListView好看。。另外TLabel有文字对齐的属性，可以看下TLabel的源码，里面有注释。

**Comment by j787701730** [comment]
谢谢
