### ISSUE TITLE
liblcl subset..

### ISSUE THREAD

**Issue by Ruxton** [ying32/govcl#74]
It'd be nice to be able to bundle the app with a subset of liblcl that only included the components used.

Hauling a large library around for a tiny application is a bit silly.

**Comment by ying32** [comment]
我无法满足每个人不同的需求，只能将所有组件放在一起。
如果有需要，可以自己精简。(I can't meet the different needs of everyone, I can only put all the components together.
If necessary, you can streamline it yourself.)
