### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by suconghou** [ying32/govcl#76]
`LabeledEdit`  及所有输入框 不能输上文字是什么问题, 输入的文字都到终端上了, 貌似stdin 和这个GUI没有关联上.

**Comment by suconghou** [comment]
go version go1.16.3 darwin/amd64

Library Version: 2.0.10

**Comment by ying32** [comment]
如果你是用的macOS，见 [APP打包](https://gitee.com/ying32/govcl/wikis/pages?sort_id=410056&doc_id=102420)，这里有解释，如果不是那不存在这个问题。

**Comment by suconghou** [comment]
了解了, 谢谢.

**Comment by suconghou** [comment]
macOS 上是不支持Canvas 吗

**Comment by ying32** [comment]
支持啊，我例子里都有呗

**Comment by suconghou** [comment]
按照文档及目录结构打包, 双击 name.app 软件包打不开软件,没反应; 但是显示包内容双击可执行文件可以打开,有什么排查思路

**Comment by ying32** [comment]
知道结构还不行啊，你得了解几个种要的文件，像info.plist里面的内容，要填好，不会填的话直接用打包的工具生成也行啊

**Comment by suconghou** [comment]
将`liblcl.dylib` 放在了 `GOPATH` 下 ; 在其他目录调用GOPATH里的可执行文件,确实会在当前目录自动生成软件包,并运行了起来; 但是关闭后,双击这个软件包,仍是打不开,没有反应,不知道你那边也是这样吗.

**Comment by suconghou** [comment]
找到问题了, 是双击时当前目标`pwd`其实不是此文件夹目录,而是`/` 造成当前目录不可写,程序无法启动.
