### ISSUE TITLE
关于TPageControl1没有关闭按钮的问题

### ISSUE THREAD

**Issue by Jjmgx** [ying32/govcl#79]
作者您好，本人一直在用govcl开发一些windows10上的小玩意自用，最近在使用TPageControl1时，发现没有关闭按钮，不管是nboShowCloseButtons设置为true还是false都没有关闭功能，后来试着想自己加控件实现，最终因为能力有限未能做到。您能否提供下解决方案或者实例？万分感谢。

**Comment by ying32** [comment]
这个只有在linux下才有关闭按钮，其他平台都没得，可以自己使用弹出菜单方式来替代这个。
