### ISSUE TITLE
TPageControl在LCL下背景色异常

### ISSUE THREAD

**Issue by ismlsmile** [ying32/govcl#8]
在Delphi和Lazarus中都是白色，在vcl下正常，在lcl下显示为灰色

Lazarus
![lazarus](https://user-images.githubusercontent.com/1876179/43815521-ab123e36-9b02-11e8-9d11-ad78bef0b534.png)

LCL
![lcl](https://user-images.githubusercontent.com/1876179/43815522-ab4daeee-9b02-11e8-9d62-2342fbedd46a.png)

VCL
![vcl](https://user-images.githubusercontent.com/1876179/43815525-abaa6f12-9b02-11e8-9fe9-819a132b08d8.png)

**Comment by ying32** [comment]
😂 😂 😂 LCL库在dll中存在好几个已知的问题目前都处于无解状态啊 😪 ，你这个也算一个
