### ISSUE TITLE
package github.com/ying32/govcl: no Go files in C:\Users\xxx\go\src\github.com\ying32\govcl

### ISSUE THREAD

**Issue by xdeng** [ying32/govcl#80]
go get -v -u github.com/ying32/govcl 的时候
package github.com/ying32/govcl: no Go files in C:\Users\xxx\go\src\github.com\ying32\govcl  这是什么错误？

**Comment by ying32** [comment]
没拉下来吧…访问github一向有问题，多试几次吧😄
