### ISSUE TITLE
关于注册Form资源为修改为明文的建议

### ISSUE THREAD

**Issue by Jjmgx** [ying32/govcl#83]
您好！我是govcl的忠实使用者，近日将我的源码提供给朋友使用时，对方想修改窗口样式，又不想安装Lazarus，这倒把我难住了，因为我是用Lazarus画的窗口，在窗口中注册时是一个[]byte。请问作者，能否将这块优化成可修改的明文方式（如json或者xml），这样可以在不使用Lazarus时方便对窗口样式做修改。

**Comment by ying32** [comment]
这个没办法，那段字节是lazarus自己的格式，如果是小修改，可以使用代码操作下即可。
