### ISSUE TITLE
安装res2go插件后，无法编译到go

### ISSUE THREAD

**Issue by f2game** [ying32/govcl#84]
![image](https://user-images.githubusercontent.com/66696425/125206102-fa3b1280-e2b7-11eb-9eb1-8689f7af608a.png)

新项目，空窗口。什么问题？

**Comment by ying32** [comment]
不知道

**Comment by f2game** [comment]
这个问题导致Lazarus直接无法使用了，不考虑修复吗？

**Comment by ying32** [comment]
不考虑，因为我没用Lazarus 2.0.12，我文档中所有都为Lazarus 2.0.10。
