### ISSUE TITLE
以下几个是否可以直接设置

### ISSUE THREAD

**Issue by ooing** [ying32/govcl#86]
1  是否可以设置启动窗口的位置，比如右下角
2  是否可以禁止拖拉改变窗口大小
3 是否可以无边框窗口，没有菜单栏和最大化最小化关闭 这些按钮

谢谢

**Comment by ying32** [comment]
* 1、没有这种直接右下角的，自己2行代码就能搞定，正好[windowsspy](https://github.com/ying32/govcl/blob/master/samples/Windows/windowsspy)例子中就有这个右下角的。
* 2、设置下窗口的`Constraints`属性即可。
* 3、设置下窗口的`BorderStyle`为`types.BsNone`即可。

**注：多看看例子，你要的这些例子里面全部都有，不然例子写了不等于白写的啊。**

**Comment by ooing** [comment]
@ying32  好的 我直接IDE里面找了半天没找到 谢谢

**Comment by ooing** [comment]
@ying32   
f.Height()   获取的高度 并不包括 标题栏的高度  标题栏高度可以获取吗

**Comment by ying32** [comment]
windows下可以尝试Height－ ClientHeight或者调用winapi  GetSystemMetrics(SM_CYCAPTION)具体准确度你还是自己查查资料吧😟

**Comment by ooing** [comment]
@ying32   好的 ，vcl.Application.SetMainFormOnTaskBar(false)  为什么无效  在任务栏还是显示图标

**Comment by ying32** [comment]
这又不是管这个的…

**Comment by ooing** [comment]
@ying32   可否任务栏不显示 程序图标

**Comment by ying32** [comment]
任务栏不显示图标？你这话我有点听不懂啊，你可以截个图具体说明下？

**Comment by ooing** [comment]
我想 任务栏不要显示这个图标
![](https://s3.bmp.ovh/imgs/2021/12/2883897c342c2b8a.png)

**Comment by ying32** [comment]
你这不是啥将图标隐藏。。你这是不在任务栏显示。
```go
// windows
// 先将  主窗口显示在任务栏 设置为false
vcl.Application.SetMainFormOnTaskBar(false)

// 再将另用winapi设置下
win.SetWindowLong(vcl.Application.Handle(), win.GWL_EXSTYLE, uintptr(win.GetWindowLong(vcl.Application.Handle(), win.GWL_EXSTYLE)|win.WS_EX_TOOLWINDOW))
```

**Comment by ooing** [comment]
> windows下可以尝试Height－ ClientHeight或者调用winapi GetSystemMetrics(SM_CYCAPTION)具体准确度你还是自己查查资料吧😟

有需要可以用下面这个试试看 谷歌搜索的
barHeight := win.GetSystemMetrics(w32.SM_CYCAPTION) +
		win.GetSystemMetrics(w32.SM_CYFRAME) + win.GetSystemMetrics(92)
