### ISSUE TITLE
能不能设置窗口任意移动，或者方法

### ISSUE THREAD

**Issue by oshellhahaha** [ying32/govcl#89]
将窗口设置成无边框，简单美化

**Comment by ying32** [comment]
https://github.com/ying32/govcl/blob/master/samples/imageviewer/MainFormImpl.go     

353、357、368行。。。

**Comment by oshellhahaha** [comment]
大佬，赞助支持了，不知有无交流群呢？

**Comment by ying32** [comment]
谢谢支持，交流群满了，暂也不开放群了。

**Comment by ooing** [comment]
@oshellhahaha   无边框后  您怎么移动的 
 SetOnEndDrag ？
