### ISSUE TITLE
autoBindEvents 有个小bug,绑定成功却有错误提示

### ISSUE THREAD

**Issue by Omiga3721** [ying32/govcl#93]
res2go 直接生事件, 验证点击事件生效,但有错误提示, 按钮的名称别是
ButtonSaveDist
ButtonSaveDistAs
ButtonSaveDistToXML

<img width="507" alt="WX20211029-161651@2x" src="https://user-images.githubusercontent.com/24944112/139400633-d662e34f-f03c-4975-8f13-1bb6bcf1ff86.png">

点击结果:
```
Library Version: 2.0.10
AESForm.ButtonSaveDist does not support the AsClick event.
AESForm.ButtonSaveDist does not support the ToXMLClick event.
OnButtonSaveDistClick
OnButtonSaveDistAsClick
OnButtonSaveDistToXMLClick
```

**Comment by ying32** [comment]
不是bug，属于正常的，因为匹配没做到精准的，暂不用理会。
