### ISSUE TITLE
在windows10 默认窗口左边 右边  底部 都会多出一些空间

### ISSUE THREAD

**Issue by ooing** [ying32/govcl#98]
![](https://s3.bmp.ovh/imgs/2021/12/d213e23836f66edd.png)

请问下  如何去除
再次感谢

**Comment by ying32** [comment]
设置Form的BorderStyle， BsSingle或者BsDialog都可啊，如果上面的效果实都不满意那就只能设置为bsNone后自己弄。。。例子里也有无边框窗口的

**Comment by ooing** [comment]
您好  请问有 z-order 设置吗

**Comment by ying32** [comment]
窗口？控件？，窗口的话例子里有一个windowsspy的。。。也是在右下角，还有置顶操作。

**Comment by ooing** [comment]
> 您好 请问有 z-order 设置吗

BringToFront
