### ISSUE TITLE
可否全局自定义字体和  NewImageButton图片模糊

### ISSUE THREAD

**Issue by jiudu12** [ying32/govcl#99]
1  可以全局设置默认 微软雅黑或其他字体 ？ 或者对控件 ？

2 我在用 NewImageButton 中图片模糊 有锯齿  ，我的图片是128*128
``` go
f.BtnClose = vcl.NewImageButton(f)
f.BtnClose.SetParent(f)
f.BtnClose.Picture().LoadFromBytes(resource.EmBedClose)
f.BtnClose.SetImageCount(1)
f.BtnClose.SetWidth(20)
f.BtnClose.SetHeight(20)
```

谢谢

**Comment by ying32** [comment]
1、没有全局的，不过你可以在每个`OnFormCreate`时设置 `f.Font().SetName("微软雅黑")`，这样当前窗口的字体都会是这个。
2、这不很正常么，ImageButton中绘制用的`StretchDraw`拉伸操作的，想要没有这些，应该做相应大小的图片。

**Comment by ying32** [comment]
2k啊。那这个控件暂时没适配2k的。。。

**Comment by jiudu12** [comment]
f.ScaleForPPI(96)  
ScaleIndex = vcl.Screen.PixelsPerInch() / 96

我这样子 可以
